### ISSUE TITLE
Order placement error

### ISSUE THREAD

**Issue by ash21213** [Chavithra/degiro-connector#100]
def PLACEORDER(vid):
  # SETUP ORDER
  order = Order(
      action=Order.Action.BUY,
      order_type=Order.OrderType.LIMIT,
      price=10,
      product_id=vid,
      size=1,
      time_type=Order.TimeType.GOOD_TILL_DAY,
  )
  
def BUY_ORD():
    SSSYM = result[result['name'] == FSCR.get()]   #Getting the DFrame of selected symbol from combobox
    selsym=SSSYM['id']
    sym=str(selsym[0])
    vid=sym
    PLACEORDER(int(vid))

While trying to place a limit order, i am getting the following error.  

CRITICAL:degiro_connector.trading.actions.action_check_order:404
CRITICAL:degiro_connector.trading.actions.action_check_order:{"errors":[{"text":"No corresponding resource found"}]}
confirmation_id = checking_response.confirmation_id
AttributeError: 'NoneType' object has no attribute 'confirmation_id

**Comment by Chavithra** [comment]
Hello there,

the library models have changed since this issue was opened.

Maybe you can try with the new examples.

Closing this issue, feel free to open a new one if you still have questions.

Thanks
