### ISSUE TITLE
Order placement error

### ISSUE THREAD

**Issue by ash21213** [Chavithra/degiro-connector#101]
Got the below errors while trying to place from order.py 

DEBUG:degiro_connector.trading.api:setup_one_action : check_order
DEBUG:degiro_connector.trading.api:setup_one_action : confirm_order
DEBUG:degiro_connector.trading.api:setup_one_action : connect
DEBUG:degiro_connector.trading.api:setup_one_action : create_favourite_list
DEBUG:degiro_connector.trading.api:setup_one_action : delete_favourite_list
DEBUG:degiro_connector.trading.api:setup_one_action : delete_favourite_list_product
DEBUG:degiro_connector.trading.api:setup_one_action : delete_order
DEBUG:degiro_connector.trading.api:setup_one_action : get_account_info
DEBUG:degiro_connector.trading.api:setup_one_action : get_account_overview
DEBUG:degiro_connector.trading.api:setup_one_action : get_agenda
DEBUG:degiro_connector.trading.api:setup_one_action : get_cash_account_report
DEBUG:degiro_connector.trading.api:setup_one_action : get_client_details
DEBUG:degiro_connector.trading.api:setup_one_action : get_company_profile
DEBUG:degiro_connector.trading.api:setup_one_action : get_company_ratios
DEBUG:degiro_connector.trading.api:setup_one_action : get_config
DEBUG:degiro_connector.trading.api:setup_one_action : get_estimates_summaries
DEBUG:degiro_connector.trading.api:setup_one_action : get_favourites_list
DEBUG:degiro_connector.trading.api:setup_one_action : get_financial_statements
DEBUG:degiro_connector.trading.api:setup_one_action : get_latest_news
DEBUG:degiro_connector.trading.api:setup_one_action : get_news_by_company
DEBUG:degiro_connector.trading.api:setup_one_action : get_orders_history
DEBUG:degiro_connector.trading.api:setup_one_action : get_position_report
DEBUG:degiro_connector.trading.api:setup_one_action : get_products_config
DEBUG:degiro_connector.trading.api:setup_one_action : get_products_info
DEBUG:degiro_connector.trading.api:setup_one_action : get_top_news_preview
DEBUG:degiro_connector.trading.api:setup_one_action : get_transactions_history
DEBUG:degiro_connector.trading.api:setup_one_action : get_update
DEBUG:degiro_connector.trading.api:setup_one_action : logout
DEBUG:degiro_connector.trading.api:setup_one_action : product_search
DEBUG:degiro_connector.trading.api:setup_one_action : put_favourite_list_product
DEBUG:degiro_connector.trading.api:setup_one_action : update_favourite_list
DEBUG:degiro_connector.trading.api:setup_one_action : update_order
DEBUG:degiro_connector.core.models.model_session:session:getter: MainThread
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): trader.degiro.nl:443
DEBUG:urllib3.connectionpool:https://trader.degiro.nl:443 "POST /login/secure/login HTTP/1.1" 200 None
INFO:degiro_connector.trading.actions.action_connect:get_session_id:response_dict: {'isPassCodeEnabled': True, 'locale': 'de_DE', 'redirectUrl': 'https://trader.degiro.nl/trader/', 'sessionId': 'DCA2034F95D4F26484B1EBDB7E024C2C.prod_a_168_4', 'status': 0, 'statusText': 'success'}
DEBUG:degiro_connector.core.models.model_session:session:getter: MainThread
DEBUG:urllib3.connectionpool:https://trader.degiro.nl:443 "POST /trading/secure/v5/checkOrder;jsessionid=DCA2034F95D4F26484B1EBDB7E024C2C.prod_a_168_4?intAccount=0&sessionId=DCA2034F95D4F26484B1EBDB7E024C2C.prod_a_168_4 HTTP/1.1" 404 None
CRITICAL:degiro_connector.trading.actions.action_check_order:404
CRITICAL:degiro_connector.trading.actions.action_check_order:{"errors":[{"text":"No corresponding resource found"}]}
Traceback (most recent call last):
  File "f:\degiro-connector-main\examples\trading\order.py", line 49, in <module>
    confirmation_id = checking_response.confirmation_id
AttributeError: 'NoneType' object has no attribute 'confirmation_id'

**Comment by ash21213** [comment]
Hi @Salinatorimperator ,

Try this. Its working fine 

ord = Order(action=Order.Action.BUY,order_type=Order.OrderType.LIMIT,price=round(float(bp),2),product_id=int(pid),size=int(qty),time_type=Order.TimeType.GOOD_TILL_DAY,) if BS=="B" else Order(action=Order.Action.SELL,order_type=Order.OrderType.LIMIT,price=round(float(bp),2),product_id=int(pid),size=int(qty),time_type=Order.TimeType.GOOD_TILL_DAY,)        

        print(ord)
            checking_response = trading_api.check_order(order=ord)
            confirmation_id = checking_response.confirmation_id
            
        confirmation_response = trading_api.confirm_order(confirmation_id=confirmation_id, order=ord)        
        print(confirmation_response.order_id  )

**Comment by Salinatorimperator** [comment]
Hi @ash21213 for me was that i was creating the tradingAPI without the int_account. Once I added that to the credentials creating the object, it worked fine.
Thanks nevertheless!!
I think this can be closed @Chavithra
