### ISSUE TITLE
password encryption-decryption

### ISSUE THREAD

**Issue by AureliusMarcusHu** [Chavithra/degiro-connector#105]
First i would like to express my thanks for this awesome degiro-api. I'm new to using this package, so please forgive me if I ask a stupid question. Do you use an encryptor-decryptor for user name and password with the login module ? Or are they just visible in the login script, or stored in a readable file ?

**Comment by Chavithra** [comment]
Hello @AureliusMarcusHu,

it depends on what you need.

If it's just for testing, a quick way is to put the credentials into a file `config/config.json`:
```json
{
    "user_token":123,
    "int_account":123,
    "username":"YOUR_USERNAME",
    "password":"YOUR_PASSWORD",
    "totp_secret_key":"OPTIONAL_TOTP_SECRET_KEY"
}
```

You might want to ignore this file from your project `.gitignore`.

I hope that helps you and other people that might read this.

Thanks
