### ISSUE TITLE
Historical prices?

### ISSUE THREAD

**Issue by AlphaJack** [Chavithra/degiro-connector#108]
Is there a way to obtain historical prices for a product given a specific date or a date interval?

**Comment by hyperfraise** [comment]
I'm interested in this too

**Comment by Chavithra** [comment]
Hello @AlphaJack,

these are the Chart related methods.

I just improved the Chart formatting : you should be able to retrieve and have a formatted DataFrame version of these timeseries.

I hope the documentation and the examples are explicit enough.

Let me know if you need more information.

Thanks

**Comment by hyperfraise** [comment]
You didn't link anything @Chavithra

**Comment by Chavithra** [comment]
@hyperfraise It is the section called `2.3. How to get a Chart ?` in the documentation.

Hope that helps
