### ISSUE TITLE
conda installation of degiro_connector

### ISSUE THREAD

**Issue by lucaga** [Chavithra/degiro-connector#113]
On this page:
`https://anaconda.org/piiq/degiro_connector`

It provides details to install degiro_connector with conda.:
`conda install -c piiq degiro_connector`

When the suggested line is entered, the conda command (in verbose mode) returns:
`Collecting package metadata (current_repodata.json): ...working... INFO conda.gateways.repodata:conda_http_errors(203): Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/piiq/linux-64/current_repodata.json`

On the page
`https://conda.anaconda.org/piiq/linux-64`
the file` current_repodata.json` doesn't exists. Instead a `repodata.json` can be found.

The installation procedure doesn't mention the conda possibility, and I would understand if this was intentional. However, the piiq repository is up to date with the last version of degiro_connector.

I am assuming that renaming the present `repodata.json` into ` current_repodata.json` would solve the issue and enable conda to proceed with the installation from the piiq channel.

What is the idea behind the existence of the piiq repository on conda?
Who could test my assumption and (maybe) enable the installation procedure through conda ?

**Comment by Chavithra** [comment]
Hello there,

> What is the idea behind the existence of the piiq repository on conda? Who could test my assumption and (maybe) enable the installation procedure through conda ?

These are some tests related to another open source project that has `degiro-connector` among it's dependency.

I think for now only a MacOS version was built.

No conda installation is planned for this quarter.

Thanks

**Comment by lucaga** [comment]
Dear Chavithra,

Thanks for the quick reply, appreciated.
Regards

**Comment by lucaga** [comment]
Dear Chavithra,

With a bit of effort, I managed to obtain the degiro_connector package installed in a conda environment.

Qualitatively, this is what I've done:
created a conda version of the onetimepass package with conda skeleton, conda-build -c local commands
installed onetimepass
installed poetry (not sure if it is 100% needed)
prepared for the creation of a conda version of the degiro_connector (very important UNDERSCORE) package with conda skeleton, 
Modified the meta.yaml addind poetry in all resources sections
created the package with conda-build -c local commands
 

is it interesting to write down these steps  in a more quantitative way?
