### ISSUE TITLE
quotecast timeouting 

### ISSUE THREAD

**Issue by pereira1408** [Chavithra/degiro-connector#120]
Dear community, 

I'm facing an issue with vwdservices to get stock prices since last Friday. Since then, seeking for a solution, I've updated all the outdated packages (didn't work). Here is the log when I try to run the realtime_one_shot.py example: 

INFO:degiro_connector.quotecast.api:Connection required.
CRITICAL:degiro_connector.quotecast.actions.action_connect:HTTPSConnectionPool(host='degiro.quotecast.vwdservices.com', port=443): Max retries exceeded with url: /CORS/request_session?version=1.0.20201211&userToken=_[REDACTEDTOKEN]_(Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020B17A4EE30>, 'Connection to degiro.quotecast.vwdservices.com timed out. (connect timeout=None)'))  

At first, I thought that I was banned or something like that, however, I can connect normally to "https://business-customer.vwd.com/chartanalyse/web/?config=degiro&_[ETC.ETC.ETC]_"

Does anyone have a clue?
Thanks in advance :)

**Comment by Chavithra** [comment]
Hello @pereira1408,

realtime data are still working on my side.

Maybe it was a connection or server issue.

An alternative is to use the Chart methods.

Closing the issue for now, feel free to reopen it or create a new one if you still have this issue.

Thanks
