### ISSUE TITLE
orjson dependency missing

### ISSUE THREAD

**Issue by nickvanc** [Chavithra/degiro-connector#125]
Hi,

I think 'orjson' is missing as a dependency.
Seen in degiro-connector 3.0.6.

Thanks! Great package.

**Comment by Chavithra** [comment]
Hello @nickvanc,

fixed the issues the new version.

Thanks for letting me know !

I am currently refactoring the library to replace:
- `protbuf` with `pydantic`
- `pandas` with `polars`

There might be few bugs coming with this.

Some improvements were made:
- helper charts into DataFrame
- fixing the favourite list methods
- models simpler to use

**Comment by nickvanc** [comment]
@Chavithra  thank!

If I run into new bugs I’ll report them.
Thanks for sharing and Happy New Year ✌️
