### ISSUE TITLE
URL of favorites list has changed

### ISSUE THREAD

**Issue by ferremek** [Chavithra/degiro-connector#126]
Hey, 

First of all, thanks a lot for this repo!

I just want to let you know that the URL of the favorites list has changed. This is in `degiro_connector/core/constants/urls.py` and the constant `PRODUCT_FAVOURITES_LISTS`, the new URL is `https://trader.degiro.nl/favorites/secure/v1`. 

I have tested this and only works like `trading_api.get_favourites_list(raw=True)`. When `raw=False` there is an error:
_Failed to parse values field: Message type "degiro_connector.trading.Favourites.List" has no field named "default" at "Favourites.values[0]".
 Available Fields(except extensions): "['id', 'name', 'isDefault', 'productIds']"._

**Comment by Chavithra** [comment]
Hello @ferremek,

this was fixed already on the more recent versions.

Thanks

**Comment by ferremek** [comment]
Hey @Chavithra, thanks for the quick reply! And yes, I had a old version installed because my Python was outdated.

Thanks again!
