### ISSUE TITLE
Extend LeveragedsRequest class

### ISSUE THREAD

**Issue by MaartenMJR** [Chavithra/degiro-connector#127]
Add optional `underlying_product_id` and `shortlong` support for `LeveragedsRequest`

**Comment by MaartenMJR** [comment]
@Chavithra for me it is convenient to select on `underlying_product_id`, I'd suggest to make this an optional input for backwards compatibility purposes.


Thanks anyway for this great python package!

**Comment by Chavithra** [comment]
Hi @MaartenMJR,

just merged PR #128.

These fields will be available on next release.

Thanks
