### ISSUE TITLE
Unwanted console output

### ISSUE THREAD

**Issue by AureliusMarcusHu** [Chavithra/degiro-connector#130]
Dear Chavithra,

Below you will find the function of the favorites request. The function works fine, but there is a unwanted console output of the data. As you can see in the function I never ask for a console output of the data. (see console output below).

**How surpress or disable this unwanted console output ?**

``` python
def favorites(show=None):

    global trapi
    show = True if show or show is None else show
    prdsd = {}
    flnm = 'favorites_dgr.jsn'
    resp = trapi.get_favorite(raw=True)
    favs = resp.get('data', {})

    for it in favs:
        fvnm = it.get('name', False)
        if fvnm:
            prdlst = it.get("productIds")
            prdlst = sorted(prdlst)
            prod_dat = trapi.get_products_info(product_list=prdlst, raw=True, )
            prdsd[fvnm] = prod_dat.get('data', {})

    save_json(prdsd, fnm=flnm, mp='data', show=show)

    return
```

**Console output**
![console_output](https://github.com/Chavithra/degiro-connector/assets/25880296/83884262-ce08-4890-82d7-b154c6afae69)

**Comment by Chavithra** [comment]
Hello @AureliusMarcusHu,

thanks for reporting this bug.

It was fixed on the last release.

Thanks
