### ISSUE TITLE
Valid search but without products found trading.actions.action_product_search

### ISSUE THREAD

**Issue by nickvanc** [Chavithra/degiro-connector#131]
**Problem:**
logger.fatal is maybe to heavy for this common use case, search without products found.

**Reproduction:** 
search "FR0007075494"
![image](https://github.com/Chavithra/degiro-connector/assets/25899773/03e06d72-3f90-4ce5-b0f5-c63aa661026e)

2024-01-10 00:17:47 - degiro_connector.trading.actions.action_product_search [CRITICAL] 1 validation error for ProductBatch
products
  Field required [type=missing, input_value={'total': 0, 'offset': 0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing    File ".\degiro_connector\trading\actions\action_product_search.py", line 136

**Comment by Chavithra** [comment]
Hello @nickvanc,

made it optional on last release.

Nice catch !

Thanks
