### ISSUE TITLE
TickerToDF.parse() problem when parsing ticker of vwd_id '61316189'

### ISSUE THREAD

**Issue by nickvanc** [Chavithra/degiro-connector#132]
**Problem:**
![image](https://github.com/Chavithra/degiro-connector/assets/25899773/7a83164b-5778-4c56-ae56-e9a7f6799465)

**Reproduction:** 
Fetch ticker with vwd_id: '61316189'
Then TickerToDF.parse()

Stack trace:
from_ticker_to_message_list, ticker_to_metric_list.py:194
parse, ticker_to_metric_list.py:244
parse, ticker_to_df.py:162

**Comment by Chavithra** [comment]
Hello @nickvanc,

looks like `61316189` is not a valid `vwd_id`.

How did you find this identifer?

Thanks

**Comment by nickvanc** [comment]
hi @Chavithra,
Through product search of `LU0533032859`.

Returns:
`[
  {
    'id': '4622348',
    'name': 'Lyxor UCITS ETF MSCI World Financials TR C-EUR',
    'isin': 'LU0533032859',
    'symbol': 'FINSW',
    'contractSize': 1.0,
    'productType': 'ETF',
    'productTypeId': 131,
    'tradable': True,
    'category': 'H',
    'currency': 'EUR',
    'active': True,
    'exchangeId': '608',
    'onlyEodPrices': False,
    'orderTimeTypes': [
      'DAY',
      'GTC'
    ],
    'buyOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLIMIT'
    ],
    'sellOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLIMIT'
    ],
    'productBitTypes': [],
    'closePrice': 237.43,
    'closePriceDate': '2024-01-09',
    'isShortable': False,
    'feedQuality': 'D15',
    'orderBookDepth': 0,
    'vwdIdentifierType': 'issueid',
    'vwdId': '300099826',
    'qualitySwitchable': True,
    'qualitySwitchFree': False,
    'vwdModuleId': 12,
    'etfIssuerId': 42,
    'feeType': 1,
    'region': 'Worldwide',
    'totalExpenseRatio': 0.3,
    'quoteCurrency': 'EUR',
    'assetAllocation': 'Shares',
    'administrator': 'Amundi Luxembourg S.A.',
    'benchmark': 'MSCI Daily TR World Net Financials USD',
    'etpType': 1
  },
  {
    'id': '1742309',
    'name': 'Lyxor UCITS ETF MSCI World Financials TR C-EUR',
    'isin': 'LU0533032859',
    'symbol': 'FINW',
    'contractSize': 1.0,
    'productType': 'ETF',
    'productTypeId': 131,
    'tradable': True,
    'category': 'H',
    'currency': 'EUR',
    'active': True,
    'exchangeId': '710',
    'onlyEodPrices': False,
    'orderTimeTypes': [
      'DAY',
      'GTC'
    ],
    'buyOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLOSS',
      'STOPLIMIT'
    ],
    'sellOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLOSS',
      'STOPLIMIT'
    ],
    'productBitTypes': [],
    'closePrice': 237.356,
    'closePriceDate': '2024-01-09',
    'isShortable': False,
    'feedQuality': 'R',
    'orderBookDepth': 0,
    'vwdIdentifierType': 'issueid',
    'vwdId': '61316189',
    'qualitySwitchable': False,
    'qualitySwitchFree': False,
    'vwdModuleId': 1,
    'etfIssuerId': 42,
    'feeType': 1,
    'region': 'Worldwide',
    'totalExpenseRatio': 0.3,
    'quoteCurrency': 'EUR',
    'assetAllocation': 'Shares',
    'administrator': 'Amundi Luxembourg S.A.',
    'benchmark': 'MSCI Daily TR World Net Financials USD',
    'etpType': 1
  },
  {
    'id': '3234880',
    'name': 'Lyxor UCITS ETF MSCI World Financials TR C-EUR',
    'isin': 'LU0533032859',
    'symbol': 'LYPD',
    'contractSize': 1.0,
    'productType': 'ETF',
    'productTypeId': 131,
    'tradable': True,
    'category': 'H',
    'currency': 'EUR',
    'active': True,
    'exchangeId': '194',
    'onlyEodPrices': False,
    'orderTimeTypes': [
      'DAY',
      'GTC'
    ],
    'buyOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLOSS',
      'STOPLIMIT',
      'TRAILINGSTOP'
    ],
    'sellOrderTypes': [
      'LIMIT',
      'MARKET',
      'STOPLOSS',
      'STOPLIMIT',
      'TRAILINGSTOP'
    ],
    'productBitTypes': [],
    'closePrice': 238.2,
    'closePriceDate': '2024-01-09',
    'isShortable': False,
    'feedQuality': 'D15',
    'orderBookDepth': 0,
    'vwdIdentifierType': 'issueid',
    'vwdId': '480012233',
    'qualitySwitchable': False,
    'qualitySwitchFree': False,
    'vwdModuleId': 25,
    'etfIssuerId': 42,
    'feeType': 1,
    'region': 'Worldwide',
    'totalExpenseRatio': 0.3,
    'quoteCurrency': 'EUR',
    'assetAllocation': 'Shares',
    'administrator': 'Amundi Luxembourg S.A.',
    'benchmark': 'MSCI Daily TR World Net Financials USD',
    'etpType': 1
  }
]`

**Comment by Chavithra** [comment]
I hope the last message helped.

Closing this issue.
