### ISSUE TITLE
Unable to place an order

### ISSUE THREAD

**Issue by lstumme** [Chavithra/degiro-connector#137]
Every time I try to place an order, following the example provided, I get the following error following the call to the check_order method:

1 validation error for CheckingWrapper
data.freeSpaceNew
  Field required [type=missing, input_value={'confirmationId': '7b2b3...ExAnteReportLink': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

For all intents and purposes, I would like to point out that I am trying to place an order on leveraged products.

**Comment by rahulbera** [comment]
Facing the same issue here. I am trying to place a GTC order in MARKET price to an ETF product. But note that, I am testing this order placement while the market is closed. 

PS: What to pass as the `product_id` in the Order object ? Is it the `vwd_id` or just the `id` of a product?

**Comment by Chavithra** [comment]
Hello there,

I have just published a new version.

The field "freeSpaceNew" is now optional.

Let me know if you still have the issue.

Thanks

**Comment by lstumme** [comment]
Thank you for this responsiveness. This fix solved my problem perfectly.
