### ISSUE TITLE
Validation errors for TransactionsHistory: data.75.feeInBaseCurrency, data.75.orderTypeId, ...

### ISSUE THREAD

**Issue by Masterxilo** [Chavithra/degiro-connector#138]
Hi. I just started using this and wanted to get a TransactionsHistory, following

https://github.com/Chavithra/degiro-connector/blob/main/examples/trading/connection_2fa.py
https://github.com/Chavithra/degiro-connector/blob/main/examples/trading/transactions_history.py

however, I get this and it seems the returned data structure is None... what can I do?

```
60 validation errors for TransactionsHistory
data.3.feeInBaseCurrency <- mostly this error
...
data.75.feeInBaseCurrency
  Field required [type=missing, input_value={'id': ...., 'produc...transactionTypeId': 108}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing

and a few others:

data.75.orderTypeId
  Field required [type=missing, input_value={'id': ..., 'produc...transactionTypeId': 108}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
data.75.tradingVenue
  Field required [type=missing, input_value={'id': ..., 'produc...transactionTypeId': 108}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
data.76.counterParty
  Field required [type=missing, input_value={'id': ..., 'produc...transactionTypeId': 108}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
data.76.executingEntityId
  Field required [type=missing, input_value={'id': ..., 'produc...transactionTypeId': 108}, input_type=dict]
```

This probably means the api changed, i.e. the fields have different names now... or that these fields can actually be empty but this library does not support that?

**Comment by Chavithra** [comment]
Hello @Masterxilo,

I have just released a new version.

This should work now.

By the way, using the option `raw=True` you can get the data as a Python dictionnary.

Which can be handy when the Pydantic model doesn't behave as one expects. 

Thanks
