### ISSUE TITLE
update.py not working

### ISSUE THREAD

**Issue by SjoerdTimovanVliet** [Chavithra/degiro-connector#139]
Hello all,

Today, I started working with the degiro connector api. I got 2FA working, but i was trying to run the update.py example. However, any of the UpdateRequests gives me a bad request.
```
credentials = build_credentials(
    location="config/config.json",
    override={
        "username": username,
        "password": password,
        "totp_secret_key": totp,
    },
)
trading_api = TradingAPI(credentials=credentials)
trading_api.connect()

# FETCH ACCOUNT UPDATE
account_update = trading_api.get_update(
    request_list=[
        UpdateRequest(
            option=UpdateOption.ALERTS,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.CASH_FUNDS,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.HISTORICAL_ORDERS,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.ORDERS,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.PORTFOLIO,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.TOTAL_PORTFOLIO,
            last_updated=0,
        ),
        UpdateRequest(
            option=UpdateOption.TRANSACTIONS,
            last_updated=0,
        ),
    ],
    raw=True,
)

print(account_update)
```
    
 CRITICAL:degiro_connector.trading.actions.action_get_update:400 Client Error:  for url XXXXXXXXX
CRITICAL:degiro_connector.trading.actions.action_get_update:{"errors":[{"text":"Bad request"}]}
None

Anybody an idea on how to solve this?

**Comment by Chavithra** [comment]
Hello @SjoerdTimovanVliet,

I cannot reproduce this issues: the `update.py` example works for me.

Are you able to run any other example successfully?

I can take a quick look if you want to show me the exact issue.

Feel free to contact me on discord.

Thanks

**Comment by SjoerdTimovanVliet** [comment]
Hello @Chavithra  thank you for your fast response. I can run any other example without a problem. It really is only  the get_update method of the TradingAPI object.

**Comment by Chavithra** [comment]
You need to provide the `int_account` field in the Credentials model for this method to work.

My discord is on my Github profile.
