### ISSUE TITLE
Is there any way to download the Account statement as a .csv file?

### ISSUE THREAD

**Issue by matheusft** [Chavithra/degiro-connector#14]

**Comment by Chavithra** [comment]
Hello Matheus,

is it possible to indicate the location in Degiro’s website of the `csv` you are looking for ?

Thanks

**Comment by matheusft** [comment]
@Chavithra 
Login > Activity > Account statement > Export
![blur](https://user-images.githubusercontent.com/2219910/122889298-94074380-d33a-11eb-9a66-f69df856fe0d.png)

**Comment by Chavithra** [comment]
This table content can be fetched using the method `get_account_overview`.

More information about `get_account_overview` method is available in the README. 

Can add a method to fetch directly the `csv` if you are interested by this feature.

**Comment by matheusft** [comment]
fetching the csv file file directly would be very interesting

**Comment by Chavithra** [comment]
> fetching the csv file file directly would be very interesting

Ok will take a look at that when I will have some time.

Will update this `issue` once the feature is added.

> [`get_account_overview`](https://github.com/Chavithra/degiro-connector/blob/47781490af9242d80b55e348ca9a7341d96e5a4e/examples/trading/account_overview.py#L53) does not provide the ISIN values, does it?

The endpoint called by `get_account_overview` method, does not provide the `ISIN`.

It only provides what you can see in the `Account statement` table in the website and the `productId`.

**Comment by matheusft** [comment]
Humm, I see. Thank you.
This is what the csv file provides. 
![blur](https://user-images.githubusercontent.com/2219910/122909531-32040980-d34d-11eb-8aca-52e0cd5ed38d.png)
It has some extra data on top of the `get_account_overview` method.

**Comment by Chavithra** [comment]
Ok I see  `get_account_overview ` provide `productId` instead of this columns from the `csv` : 
- `Product`
- `ISIN`

The rest of the fields seems to be there.

**Comment by Chavithra** [comment]
I have published a new version of this library.

The following method was added :
- `get_cash_account_report`

This method is documented.

This should let you export in `CSV` among other formats.

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to open a new one if you have others questions.
