### ISSUE TITLE
map_elements function without return_dtype in ticker_to_df

### ISSUE THREAD

**Issue by lucaga** [Chavithra/degiro-connector#140]
Thanks for this amazing code and its documentation.

A question, while testing the [realtime_poller example](https://github.com/Chavithra/degiro-connector/blob/main/examples/quotecast/realtime_poller.py), the dataframe is created by `ticker_to_py`.

the functions  
 `add_request_duration_column`
 `add_response_datetime_column` 
use the method `.map_elements`. Since the argument return_dtype is not specified, it returns a warning:

> `MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.`

When adding the dtype the warning goes away, though it leaves me asking what other consequences might happen.
It seems that the variable that is going to be written is well defined and confined by the scope of the function.

What would be against specifying the `return_dtype`?

**Comment by Chavithra** [comment]
Hi @lucaga,

I guess the right type for these columns is `pl.Datetime`.

For the impact let's see.

PR are welcome !

Thanks for this feedback

**Comment by lucaga** [comment]
PR is done.
