### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Masterxilo** [Chavithra/degiro-connector#147]
this probably came with the latest update, I saw they changed a lot e.g. in Account statement csv download, I dont see the option to extend the date range beyond 3 months anymore and deeplinks to that page restrict to one month

this is with code similar to

https://github.com/Chavithra/degiro-connector/blob/main/examples/trading/account_overview.py

```
Successfully installed degiro-connector-3.0.19
You are now connected, with the session id : 92****D.prod_dcv_ch55_4
AccountOverview - all the cash movements
502 Server Error: Bad Gateway for url: https://trader.degiro.nl/reporting/secure/v6/accountoverview?fromDate=01%2F01%2F2019&toDate=11%2F06%2F2024&sessionId=92*****3D.prod_dcv_ch55_4
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

None
TransactionsHistory - all Transactions
502 Server Error: Bad Gateway for url: https://trader.degiro.nl/reporting/secure/v4/transactions?fromDate=01%2F01%2F2019&toDate=11%2F06%2F2024&groupTransactionsByOrder=False&sessionId=92******3D.prod_dcv_ch55_4
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

None
```

**Comment by AureliusMarcusHu** [comment]
I have today the same error as described by Masterxilo. Bud I have only transaction_request (HistoryRequest) for 1 day.

**Comment by afurno** [comment]
Same here. Seems every reporting url is affected by this error. They probably changed the API endpoints

**Comment by drkthng** [comment]
> I have today the same error as described by Masterxilo. Bud I have only transaction_request (HistoryRequest) for 1 day. I run this function every day to get the daily transactions. Yesterday and in the past everything has worked fine. De-giro must have changed something.
> 
> In the url there is a difference now: with browser: /transactions?fromDate=2024-06-11&toDate=2024-06-11 with connector: /transactions?fromDate=11%2F06%2F2024&toDate=11%2F06%2F2024

I just tried to just change the date-format to yyyy-MM-dd, but I still get the 502 error, so must be something else...

**Comment by drkthng** [comment]
just found the issue, [the commit from 3 days ago](https://github.com/Chavithra/degiro-connector/commit/399ba5d414780ef7dbf025674ddcee86882c6f32) solved only part of the problem.
Actually all urls that contain  "/reporting/" need to be changed to "/portfolio-reports/"
this solved my problems at least...

**Comment by afurno** [comment]
@drkthng : it seems they have a v6 API.
For instance:
"https://trader.degiro.nl/portfolio-reports/secure/v6/accountoverview"

**Comment by Chavithra** [comment]
Hi folks,

I have just released a new version of the library with your contributions in it.

Thanks

**Comment by AureliusMarcusHu** [comment]
Guys,

After upgrading degiro_connector there is still the error "502 Bad Gateway" with "action_get_transaction_history".
Does anyone have a solution?

**Comment by Chavithra** [comment]
> @Chavithra ,
> 
> After upgrading degiro_connector there is still the error "502 Bad Gateway" with "action_get_transaction_history".
> 
> **Solution:** **_file: degiro_connector/core/constants/urls.py change line 52 to: TRANSACTIONS_HISTORY = "https://trader.degiro.nl/portfolio-reports/secure/v4/transactions"_**
> 
> Then it will work again.

The library was updated.

Thanks @AureliusMarcusHu
