### ISSUE TITLE
update_order not working

### ISSUE THREAD

**Issue by drkthng** [Chavithra/degiro-connector#15]
Hi Chavithra,
great work you did here with this api!

I have one problem though. the update_order seems not to work.

I am trying to update an existing stop-limit order (I got the orderId of this order previously)
python code:
```
order = Order(
    id=orderId,
    action=Order.Action.BUY,
    order_type=Order.OrderType.STOP_LIMIT,
    price=15.30,
    stop_price=15.20,
    product_id=18431361,
    size=1,
    time_type=Order.TimeType.GOOD_TILL_CANCELED,
)

# UPDATE ORDER
succcess = trading_api.update_order(order=order)
```

When I capture the http request I see that the body of the request looks like this:
```
{
  "buySell": 0,
  "orderType": 1,
  "price": 0,
  "productId": 18431361,
  "size": 1,
  "timeType": 3
}
```

For some reason buySell and price get set to 0 -> couldn't figure out why myself, hence this issue.

Best Regards! and keep up this amazing work!

**Comment by Chavithra** [comment]
Hello there,

thanks for reporting this bug.

Was able to reproduce it and to identify the source.

Will prepare a new release this weekend if I have enough time.

Have a nice weekend

**Comment by Chavithra** [comment]
I have just published a fix.

I am interesting on your feedback.

Thanks

**Comment by drkthng** [comment]
Hey Chavithra, 
the new version works like a charm! Just transferred an update via the api successfully!
