### ISSUE TITLE
Tolerate ticker data with LastDate but missing LastTime

### ISSUE THREAD

**Issue by Jpsy** [Chavithra/degiro-connector#157]
Some tickers do return a valid LastDate, but no valid LastTime.
If this happens, the `TickerToDF.parse()` method of Quotecast crashes when it trys to create the column LastDateTime.
I have a patch that can solve this (will create a PR for it). But please be warned that I am a Python noob guided by ChatGTP and StackOverflow.

A stock that shows this problem is NVIDIA at TDG:

    product_id = 19751774
    vwd_id = "US67066G1040.TRADE,E"

The Degiro website already shows that some data is missing for this stock symbol:

---
![image](https://github.com/user-attachments/assets/40856dd6-78bd-48fd-9208-b46425ce20de)
---

A Ticker json_text for this stock looks like this:

    [
        {
            "m": "a_req",
            "v": [
                "US67066G1040.TRADE,E.LastDate",
                8869
            ]
        },
        {
            "m": "us",
            "v": [
                8869,
                "2024-10-25"
            ]
        },
        {
            "m": "a_req",
            "v": [
                "US67066G1040.TRADE,E.LastTime",
                8868
            ]
        },
        {
            "m": "ue",
            "v": [
                8868   // <---- MISSING VALUE HERE, THIS CRASHES PARSE()
            ]
        },
        {
            "m": "a_req",
            "v": [
                "US67066G1040.TRADE,E.LastPrice",
                8872
            ]
        },
        {
            "m": "un",
            "v": [
                8872,
                131.060000
            ]
        },
        {
            "m": "a_req",
            "v": [
                "US67066G1040.TRADE,E.LastVolume",
                106807   // <---- THIS METRIC_NAME HAS NO MATCHING VALUE OBJECT, BUT THAT DOES NOT HURT
            ]
        }
    ]

As you can see, the `metric_name` for `LastTime` exists, but there is no usable value. (BTW the same is true for `LastVolume`, but that does not hurt). 

With this metric missing, the resulting `metric_list` contains only `LastDate` and `LastPrice`.
That's why `TickerToDF.parse()` crashes with:

    line 51, in build_df
      df = df.with_columns(
          (pl.col("LastDate") + " " + pl.col("LastTime")).alias("LastDatetime")
      )
    ...
    polars.exceptions.ColumnNotFoundError: LastTime

This can be easily solved by creating a LastTime with value 00:00:00 if this column does not exist. See my upcoming PR.

**Comment by Chavithra** [comment]
Hello @Jpsy,

nice explanation !

Thanks for the PR, a new release was published.
