### ISSUE TITLE
Quotecast.get_chart resolutions missing

### ISSUE THREAD

**Issue by digaph** [Chavithra/degiro-connector#16]
First off thank you very much for this very well made package.

When trying to fetch chart data using quotecast for longer periods like P1M or P3M etc I would like the resolution to be 1 day.
Looking at degiro itself it seems like a resolution code of P1D, P7D and P1M is being used in the requests, for instance:
```requestid=1
resolution=P1D
culture=nl-NL
period=P3M
series=issueid%3A613007
series=price%3Aissueid%3A613007
format=json
callback=vwd.hchart.seriesRequestManager.sync_response
userToken=???
tz=Europe%2FAmsterdam
```
Looking at the pb2 enum it seems like we only have intraday resolutions and we're missing the `P1D`, `P7D` and `P1M` resolutions.

Thanks again for the great work you're doing!

Cheers,
Michel

**Comment by Chavithra** [comment]
Hello there,

I will split my answer into three points :  
1. What is your question ?
2. Override
3. Related issue

**3. What is your question ?**
You want to add the following options to `Chart.Resolution` enum ?
- P1D
- P7D
- P1M

`Chart.Resolution` can be changed here : 
- protos/degiro_connector/quotecast/pb/quotecast.proto

Feel free to make a Pull Request, if you have tested these options.

I could then regenerate the `pb2` files.

**2. Override**
The method `get_chart` has a parameter `override`.

You can use it to override the `resolution`, like so : 
```python
chart = quotecast_api.get_chart(
    request=request,
    override={"resolution":"P1D"},
    raw=True,
)
```
More information in the comments of `get_chart` function in `degiro_connector/quotecast/utilities.py`

**3. Related issue**
Here is another issue related to chart : #9 
Just in case you might be interested in.

**Comment by digaph** [comment]
@Chavithra thank you for your answer.
I wasn't aware of the ability to override the resolution and period of the get_chart call, which is a workaround I can live with.

As for the pull request to add the `P1D`, `P7D` & `P1M` resolutions to the protobuf I ran into a conflict as P1D is already used for the Period enum and apparently it's not possible to use the same enum value twice in one proto file.

So I guess I'll switch to using the override instead.

Thanks, Michel

**Comment by Chavithra** [comment]
> As for the pull request to add the `P1D`, `P7D` & `P1M` resolutions to the protobuf I ran into a conflict as P1D is already used for the Period enum and apparently it's not possible to use the same enum value twice in one proto file.

What you are trying to do is perfectly allowed by `Protocol Buffer`.

If you are interested in the full process after updating the `quotecast.proto` file you need to run a command like this : 

```sh
python -m grpc_tools.protoc --python_out=. --grpc_python_out=. --proto_path=protos protos\degiro_connector\quotecast\pb\quotecast.proto protos\degiro_connector\trading\pb\trading.proto
```

Nice evening

**Comment by digaph** [comment]
When I run that command I get the following messages:

```
degiro_connector/quotecast/pb/quotecast.proto:57:5: "P1D" is already defined in "Chart".
degiro_connector/quotecast/pb/quotecast.proto:57:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "P1D" must be unique within "Chart", not just within "Period".
degiro_connector/quotecast/pb/quotecast.proto:59:5: "P1M" is already defined in "Chart".
degiro_connector/quotecast/pb/quotecast.proto:59:5: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "P1M" must be unique within "Chart", not just within "Period".
```

The error is explaining what I mentioned above. As both the Resolution Enum and the Period Enum are children of the Chart scope, the values within the Enum need to be unique within Chart and not just within each Enum. This limitation means that I don't know how to get both to support the same values as changing the value will not work for the external API.

A quick google search reveals many developers running into the same limitation with no real solution other than to prefix the enum values with something unique.

Cheers, Michel

**Comment by Chavithra** [comment]
You are right, I didn't knew that : 
- `enum` inside the same `message` couldn't have the same option names.

Merged `Period` and `Resolution` in a single `Interval` enum.

The modification was published and a migration script comes with it.

**Comment by digaph** [comment]
@Chavithra thank you very much. I tested it and it works like a charm.

Cheers, Michel
