### ISSUE TITLE
Is there a way to use JsessionId for authentication instead of username password or one time password

### ISSUE THREAD

**Issue by keinagae** [Chavithra/degiro-connector#17]

**Comment by Chavithra** [comment]
Hi there,

Questions : 
1. How do you get this `JsessionId` ?
2. Are you talking about the `session_id` that one can get login with his/her `username` and `password` ?

**Comment by keinagae** [comment]
I am getting it from browser local storage and i dont want to ask users for username and password

**Comment by Chavithra** [comment]
Out of curiosity : what are you trying to build ?

**Comment by keinagae** [comment]
Actually I am trying to build chrome extension and that is why i dont want users to enter their login credentials twice

**Comment by Chavithra** [comment]
In this file there is an example of how to access the `session_id` attribute :
- `examples/trading/connection.py`

Here is how to change it :
```python
trading_api= TradingAPI(credentials=credentials)
trading_api.connection_storage.session_id = "YOUR_SESSION_ID"
```

Didn't know you could build `Chrome` extension with `Python`.
How do you build such extension ?
Is it by converting `Python` to `Javascript` ?

**Comment by keinagae** [comment]
my take on it is to use vuejs for frontend and backend is in python django but yah we can convert python to js

**Comment by Chavithra** [comment]
I think the question was answered.
Closing the issue.
