### ISSUE TITLE
Products info not working for ids

### ISSUE THREAD

**Issue by keinagae** [Chavithra/degiro-connector#18]
I am trying to get products info for that i am getting {'errors': [{'text': 'No corresponding resource found'}]} even though ids are actually valid

**Comment by Chavithra** [comment]
Hello there,

which products ids are you using ?

Thanks

**Comment by keinagae** [comment]
Id that i am using is 15313242

**Comment by Chavithra** [comment]
> Id that i am using is 15313242

Will check that this weekend.

**Comment by Chavithra** [comment]
**On my side**
I can use the method `get_products_info` to fetch data about the product : `15313242`.

**Question**
Is it possible to show me the code that generates the message : `No corresponding resource found` ?

Thanks

**Comment by keinagae** [comment]
`productsRequest=ProductsInfo.Request()`
`productsRequest.products.extend([15313242])`
 `productsInfo=settings.DEGIRO_API.api.get_products_info(request=productsRequest,raw=True)`

**Comment by Chavithra** [comment]
**No issue**
> `productsRequest=ProductsInfo.Request()`
> `productsRequest.products.extend([15313242])`
> `productsInfo=settings.DEGIRO_API.api.get_products_info(request=productsRequest,raw=True)`

When I do something like that, it works.

**Issue**
So I figured out the issue might come from the connection part.

I have established a connection without providing the `int_account` then tried to use the method `get_products_info`.

Now I have this error `404` : `{'errors': [{'text': 'No corresponding resource found'}]}`

**Credentials**
You can get the `int_account` after being logged using the method `get_client_details` for instance.

More information on the `int_account` and `Credentials` are available in the documentation.

**Comment by Chavithra** [comment]
Closing this issue.
