### ISSUE TITLE
get exchange of stock

### ISSUE THREAD

**Issue by gtvCH** [Chavithra/degiro-connector#19]
Thanks for this great API-module.
Is it possible to find out on which exchange a stock is listed? Because when I have a stock (id, name or symbol via product search) I would like to know if the stock is available on the NYSE or the NASDAQ Stock Exchange.
Thank you for an answer :)

**Comment by digaph** [comment]
Hi @gtvCH,

You can use the TradingAPI.get_products_config method to fetch a list of countries, exchanges, indices, etc.
After that you should be able to match the exchange_id from the product info to an exchange you fetched using `get_products_config`.
Documentation can be found: [https://github.com/Chavithra/degiro-connector#71-how-to-get-the-table--productsconfig-]()

Hope that helps.

**Comment by gtvCH** [comment]
> Hi @gtvCH,
> 
> You can use the TradingAPI.get_products_config method to fetch a list of countries, exchanges, indices, etc.
> After that you should be able to match the exchange_id from the product info to an exchange you fetched using `get_products_config`.
> Documentation can be found: https://github.com/Chavithra/degiro-connector#71-how-to-get-the-table--productsconfig-
> 
> Hope that helps.

Thank you very much, this is the solution, it works :)
