### ISSUE TITLE
Getting quotecast data

### ISSUE THREAD

**Issue by trbck** [Chavithra/degiro-connector#2]
Hi

```
request.subscriptions['AAPL.BATS,E'].extend([
    'LastDate',
    'LastTime',
    'LastPrice',
    'LastVolume',
    'LastPrice',
    'AskPrice',
    'BidPrice',
])
```

Do you know what ",E" stands for and how would a subscription look like for a realtime stock Bayer Xetra market item (realtime data purchased within the account)?

Many thanks!

**Comment by Chavithra** [comment]
Hello trbck,

I have split my answer in two parts :
1. Do I know what the ",E" part in "AAPL.BATS,E" stand for ?
2. How to get Bayer's realtime data on the market Xetra ?

**1. Do I know what the ",E" part in "AAPL.BATS,E" stands for ?**

No, I don't.

I just understand that :
- "AAPL.BATS,E" is the "vwd_id" of this stock
- "AAPL" is the symbol of the stock.
- "BATS,E" is the part regarding the market (NASDAQ)

**2. How to get Bayer's realtime data on the market Xetra ?**

Short answer : you replace "AAPL.BATS,E" by Bayer's "vwd_id" which is : "480011639"

Assuming you are looking for this product : 
- symbol = BAYN
- market = XET
- URL : https://trader.degiro.nl/trader/#/products/3934/overview
- id = 3934

I have got the id from the URL.

**Comment by trbck** [comment]
many thanks!
