### ISSUE TITLE
quotecast parser possible issue?

### ISSUE THREAD

**Issue by matth82** [Chavithra/degiro-connector#20]
Is this type comparison right (I cannot test since I never had the a_rel being returned), list[str,str] (=vwd_id, metric) vs. str?
```
  elif message["m"] == "a_rel":
                delete_list = []
                for reference in references:
                    **if references[reference] == message["v"][0]:**
                        delete_list.append(reference)

                for reference in delete_list:
                    del references[reference]
```

**Comment by Chavithra** [comment]
Hello there,

you are right that's a bug on unsubscription parsing.

I have just released a fix.

**Comment by Chavithra** [comment]
Thank you for the bug report.

Closing this ticket.

Feel free to open another ticket if you want to give your feedback on the fix.
