### ISSUE TITLE
Historical data, and how can we help

### ISSUE THREAD

**Issue by blunderedbishop** [Chavithra/degiro-connector#22]
I see there is currently no way to fetch historical data. Would this be possible to implement? 

I would also like to help out with development. If you have a to-do list, it would be great to share it. Thanks!

**Comment by Chavithra** [comment]
Hello there,

**Historical data**
I am not sure to understand what you mean by « historical data » is it possible to send me an example ?

**Development**
I would love to get some help.
I have prepared a new structure : so people can add/modify a feature without having to look at other features code.

Also have a todo list.

Will try to share both the refactoring and the todo list this weekend.

Thanks

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to join me on discord if you want to contribute.

My contact details are on my github profile.
