### ISSUE TITLE
Using tickers

### ISSUE THREAD

**Issue by ErkkaRy** [Chavithra/degiro-connector#23]
Hi!

Thanks for the great work with the Degiro API wrapper. 

I was just wondering if there is a way to operate with tickers (e.g. 'TSLA' for Testa or 'AAPL' for Apple). Mostly in trading we operate with the tickers and e.g. if I want to fetch history data from Yahoo Finance API or extract a list of potential stocks to trade from Finviz API I have to use tickers. Tickers are also unique (at least on country level) and very practical to operate with. Probably you know all this already :). Anyway, it would be very useful to have a function to extract the stock Degiro id for a stock for a specific ticker.  

I don't know if I have missed something but I could not find a simple way to do this.

**Comment by ErkkaRy** [comment]
So something like the current product_lookup. but where you could use ticker instead and perhaps limit to specific Echanges and product types to avoid potential duplicates.

**Comment by Chavithra** [comment]
Hello there,

so you want to get the `stock detail` just by providing the `ticker symbol` ?

This might be a solution :

```python
# SETUP REQUEST
request = ProductSearch.RequestStocks(
    index_id=None,
    is_in_us_green_list=False,
    stock_country_id=None,
    offset=0,
    limit=1,
    require_total=True,
    search_text="AAPL",  # TICKER SYMBOL
    sort_columns="name",
    sort_types="asc",
)

# FETCH DATA
products = trading_api.product_search(request=request, raw=True)
```

**Comment by ErkkaRy** [comment]
Thanks a lot, I'll try this.

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to open another issue if you have questions.
