### ISSUE TITLE
how to get product ids?

### ISSUE THREAD

**Issue by fboerman** [Chavithra/degiro-connector#25]
hi!

I wanted to try out your library but I am a bit overwhelmed how to use it correctly. I would like to get some charting ID from a stock, for example for the AEX. I cant seem to find in the examples how to get the product id that belongs to a stock from a company defined by an isin. Could you provide an example for that? Thanks!

**Comment by Chavithra** [comment]
Hi,

what you are calling `charting ID` is actually called like this in Degiro`s API :
- vwdId
- issueid
- vwdIdSecondary

This list is not exhaustive.

Not to confuse with the `id` parameter which is used in Degiro`s API for some "trading related operations".

I think once you will fixed #26 and will be able to see the data it will become easier to understand for you.

If you need charts these issues might interest you :
- #9
- #4
- #2
