### ISSUE TITLE
Cannot find user_token

### ISSUE THREAD

**Issue by loopingleo** [Chavithra/degiro-connector#28]
Probably a stupid question... but how do I find my user token to login? Thanks.

**Comment by Chavithra** [comment]
Hi, you have a section dedicated to that in the documentation : 
- *2.3. How to find your : user_token ?*

**Comment by loopingleo** [comment]
> Hi, you have a section dedicated to that in the documentation :
> 
> * _2.3. How to find your : user_token ?_

Thanks - however, that did not help much. What do I need to do to get my token? Access https://trader.degiro.nl/ through a browser?

**Comment by Chavithra** [comment]
Did you try to run this file ?
- examples/trading/client_details_table.py

It will display your `user_token`.

**Comment by loopingleo** [comment]
> Did you try to run this file ?
> 
> * examples/trading/client_details_table.py
> 
> It should display your `user_token`.

It returns a file not found error:
```
➜  trading git:(main) ✗ python3.9 client_details_table.py
Traceback (most recent call last):
  File "/Users/abc/code/degiro-connector/examples/trading/client_details_table.py", line 12, in <module>
    with open("config/config.json") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
➜  trading git:(main) ✗ python3.9 client_details_table.py

```
--> what am I doing incorrectly? Do I need to create that file myself? Am I executing it incorrectly?
Thanks a lot @Chavithra

**Comment by Chavithra** [comment]
I think it would be easier if you can see that on Discord.

My Discord is on my profile.

**Comment by loopingleo** [comment]
Thanks, @Chavithra - I have created my own config directory with a config.json file storing my credentials.
My config file looks a bit like this:
```json
{
    "user_token":123,
    "int_account":123,
    "username":"myfancyusername",
    "password":"exceptionallystrongpwwhichIshouldrenewsoonIguesshaveagoodweekend"
}
```
