### ISSUE TITLE
Unclear when to use request override

### ISSUE THREAD

**Issue by fernandobrito** [Chavithra/degiro-connector#30]
Hello! 👋 

Both in the README (https://github.com/Chavithra/degiro-connector#214-how-to-get-chart-data-) and in one of the example files (https://github.com/Chavithra/degiro-connector/blob/main/examples/quotecast/chart_format.py#L40), there's a request `override` being used, but it's not clear to me when and why I should use that.

Also in my own attempts, if I do:
```
request = Chart.Request()
request.culture = self.culture
request.period = Chart.Interval.P1D
request.requestid = "1"
request.resolution = Chart.Interval.P1Y
request.series.append("ohlc:issueid:360148977")
request.tz = self.timezone

# request.override["resolution"] = "P1D"
# request.override["period"] = "P1Y"

# FETCH DATA
chart = quotecast_api.get_chart(request=request, raw=True)
```

I get no data in the response, but if I remove the comments on the overrides, then it works. Why are the overrides needed?

**Comment by Chavithra** [comment]
Hi,

what do you have in the response ?

**Comment by fernandobrito** [comment]
Aha, I actually blindly copy and pasted the example file and didn't realize that the period and resolution were incompatible.
I see that you did some updates on the examples, thanks! I will give it a try during this weekend and most likely close this issue. 🙌

**Comment by fernandobrito** [comment]
For me the example works well now, thanks.
