### ISSUE TITLE
Chart returned data incomplete?

### ISSUE THREAD

**Issue by fboerman** [Chavithra/degiro-connector#32]
hi @Chavithra  I am trying to fetch prices with chart like so:
```python
# PREPARE REQUEST
request = Chart.Request()
request.culture = "en-US"
request.requestid = "1"
request.resolution = Chart.Interval.PT1M
request.period = Chart.Interval.P1M

for stock_vwd in stocks:
    request.series.append("price:vwdkey:"+stock_vwd)
request.tz = "Europe/Paris"

# FETCH DATA
chart = quotecast_api.get_chart(
    request=request,
    raw=False,
)

ChartHelper.format_chart(chart=chart, copy=False)

df = {}
for serie in data.series:
    df_s = ChartHelper.serie_to_df(serie=serie)
    df_s["timestamp"] = pd.to_datetime(df_s["timestamp"], unit="s")
    df_s.set_index('timestamp', inplace=True)
    df[vwd_to_ticker[serie.id.split(':')[-1]]] = df_s['price']
```

here vwd_to_ticker is a dictionary which maps the vwdid to the ticker.

but when I look at the resulting data after putting it in a dataframe I noticed some strange things. First of all the number of samples per stock differs. When I join them together I get spots of 1 interval (I tried both hour and minute resolution) where data is missing for one of the two stocks.
The data also stops an hour before realtime

More strangely I can not match the data I am seeing to the UI. The UI seems to show me a different price then what I am getting back. Is this charting data the closing price per interval?

Is this a timezone issue? Am I wrong in parsing the timestamp the way I do it?

Thanks in advance for your help if possible!

**Comment by fboerman** [comment]
hi @Chavithra im sorry thats a typo my bad. I have edited the snippit to be correct

**Comment by Chavithra** [comment]
I think after changing this line too it should work :
```python
for serie in data.series:
```

**Comment by fboerman** [comment]
I don't understand, that line is already there otherwise I can't extract the multipel series.

The problem is that there are missing data points within that série?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chavithra** [comment]
Here you use a `data` variable :
```python
for serie in data.series:
```

This `data` variable is not defined in the example you have shown.

Should it be  like the following ?
```python
for serie in chart.series:
```

**Comment by fboerman** [comment]
hi @Chavithra hmm it seems I copied from my notebook which is messed up in saving, happened to me before. sorry for the confusion.

below is a function I wrote in a seperate script which is correct:
```python
    @reconnect
    def get_prices(self, df_stocks, period=Chart.Interval.P6M):
        """
        stocks need to be a dataframe with at least the columns: symbol, vwdIdSecondary

        :param stocks:
        :param period:
        :return:
        """
        request = Chart.Request()
        request.culture = "en-US"
        request.requestid = "1"
        request.resolution = Chart.Interval.PT1H
        request.period = period
        for stock_vwd in df_stocks['vwdIdSecondary']:
            request.series.append("price:vwdkey:"+stock_vwd)
        request.tz = "Europe/Paris"

        data = self.quotecast_api.get_chart(
            request=request,
            raw=False,
        )
        ChartHelper.format_chart(chart=data, copy=False)
        vwd_to_ticker = dict(zip(df_stocks['vwdIdSecondary'], df_stocks['symbol']))

        df = {}
        for serie in data.series:
            df_s = ChartHelper.serie_to_df(serie=serie)
            df_s["timestamp"] = pd.to_datetime(df_s["timestamp"], unit="s")
            df_s.set_index('timestamp', inplace=True)
            df[vwd_to_ticker[serie.id.split(':')[-1]]] = df_s['price']

        return df
```
this returns a dictionary with series. not a dataframe yet because of the following issues.

when I merge two series in a dataframe like this:
```python
df1=pd.DataFrame({'AAPL': p['AAPL']})
df2=pd.DataFrame({'GOOGL': p['GOOGL']})
df3=df1.join(df2, how='outer')
```
then I get gaps like this:
![Screen Capture_select-area_20211120123030](https://user-images.githubusercontent.com/4730734/142724715-486140be-66b6-49a1-a532-d4fe893f1c99.png)

furthermore when I look at the UI at this moment the last price for AAPL and GOOGL is:
![Screen Capture_select-area_20211120123248](https://user-images.githubusercontent.com/4730734/142724778-541b2b4f-9358-4b2d-ade8-c3d6991829dd.png)
![Screen Capture_select-area_20211120123236](https://user-images.githubusercontent.com/4730734/142724780-62ac96f5-d2df-4ba8-a326-e940b46939ca.png)

but the dataframe shows:

![Screen Capture_select-area_20211120123330](https://user-images.githubusercontent.com/4730734/142724791-c42dc1a6-1f18-463e-b082-2fb54bc3d44b.png)

if I try to match specific pricepoints to the UI I get teh same problem.

do you know what is going wrong here? I hope this explanation makes it more clear

**Comment by Chavithra** [comment]
I have checked the data and this seems to fit what the API is returning.

Looks like when you choose a `PT1H` `resolution` : it can display multiple recording within the same hour.

Though, the recordings seem to be valid ones.

For instance, if you filter with `PT1M` (1 minute) `resolution` you will have the following values  :

|**timestamp**|**AAPL price**|**GOOGL price**|
|:-|:-|:-|
|2021-11-19 20:42:00|161.015|2980.56|
|2021-11-19 20:59:00|160.58|2977.98|


Which match with the following values for `PT1H` (1 hour) `resolution` :

|**timestamp**|**AAPL price**|**GOOGL price**|
|:-|:-|:-|
|2021-11-19 20:00:00|161.015|2977.98|
2021-11-19 20:00:00|160.58|2977.98|

N.B. : looks like it's one hour earlier on your side :p

Hope that helps

**Comment by fboerman** [comment]
hi @Chavithra thank you for the answer.

so if I fully understand you the price for hour is a rounding point in that hour? that would be a bit weird? But I guess for the purpose of showing the trend its possible.

**Comment by Chavithra** [comment]
> hi @Chavithra thank you for the answer.
> 
> so if I fully understand you the price for hour is a rounding point in that hour? that would be a bit weird? But I guess for the purpose of showing the trend its possible.

From the data I saw : it looks like they pick some values within a specific hour.

I also don't get why they don't just put one value : the closest record they have to this specific hour.

Also beware : all this is a guessing from that quick test I made.

**Comment by fboerman** [comment]
hi @Chavithra  okay that makes sense I guess. Not sure what is the best way to check that right now. Do you have an idea why points are missing?

**Comment by Chavithra** [comment]
> hi @Chavithra okay that makes sense I guess. Not sure what is the best way to check that right now. Do you have an idea why points are missing?

Since that's the way data is returned from the API I think you can only postprocess it or search for a another way to get it.

Closing this issue.

Feel free to open a new one or ping me on Discord if you have another question.
