### ISSUE TITLE
404 in ProductSearch

### ISSUE THREAD

**Issue by alirezamdv** [Chavithra/degiro-connector#35]
Hi, thanks for sharing your nice work.
This method  ProductSearch.**RequestStocks(**) returns 404.
This is the request url:
https://trader.degiro.nl/product_search/secure/v5/stocks?intAccount=0&sessionId=*****prod_b_127

![image](https://user-images.githubusercontent.com/40889755/144271172-d520c2e6-2fdd-4dbd-ad3f-f64d64f61447.png)

**Comment by alirezamdv** [comment]
I fixed with commenting the "intAccount" parameter in product_search. It works for me.

**Comment by Chavithra** [comment]
Hello Alireza,

I learn something there :
- didn't know that when you remove the `intAccount` it was still working.

This library tends to simulate as much as possible how the website behave : and the website sends the `intAccount`.

More information on the `int_account` on this section of the documentation :
- *3.4. How to find your : int_account ?*

If you really don't want to send you `intAccount` one solution would be to add a condition to avoid sending it when :
- `intAccount=0`

**Comment by alirezamdv** [comment]
Thanks for fast reply. You are right, I just set the intAccount in the credential and it works correctly, but it also works without setting the intAccount, so if the intAccount is not set, we can take it out from URL.
