### ISSUE TITLE
bid & ask size?

### ISSUE THREAD

**Issue by 123m321** [Chavithra/degiro-connector#37]
First of all many thanks, this is really great work Chavithra!

I have a few questions. Would it be possible to the the size of the bid and ask? We can get the bidPrice and askPrice, but for how many shares is this (or contracts, in the derivates market)?

And second, is it possible to get a snapshot of the dept of the orderbook?

**Comment by Chavithra** [comment]
Hello there,

**Bid and Ask**
You can get the following information using the `fetch_data` method from the `quotecast.api` module :
- ask price
- ask volume
- bid price
- ask volume

**Which products ?**
I guess your question was about : knowing for which `products` you can get this `bid/ask` data ?

It seems to work on most of the product types : `stocks`, `currencies`, `etfs`, `bond`...

Beware : not all product data can be accessed in real-time.

But whenever a real-time `metric` is available on the website you can most likely get it through this library.

**Which products ?**

> And second, is it possible to get a snapshot of the dept of the orderbook?

Do you mean access to the history ?

As far as I know you can`t access to the orderbook history through the API.

But you can get the dept.

**Comment by 123m321** [comment]
Thanks! 

With the orderbook I mean what's in the depth of the market.  

Say a stock is quoted 20.00 at 20.05 (for 500 shares on both sides). But what's the bid behind? You can see at DG website what's the second best bid (say, 19.99 for 50000 shares). And behind that 19.97 for 500. 

For many products you can see the orderbook realtime.

**Comment by funnel20** [comment]
> Hello there,
> 
> **Bid and Ask** You can get the following information using the `fetch_data` method from the `quotecast.api` module :
> 
> * ask price
> * ask volume
> * bid price
> * ask volume
> 
> **Which products ?** I guess your question was about : knowing for which `products` you can get this `bid/ask` data ?
> 
> It seems to work on most of the product types : `stocks`, `currencies`, `etfs`, `bond`...
> 
> Beware : not all product data can be accessed in real-time.
> 
> But whenever a real-time `metric` is available on the website you can most likely get it through this library.
> 
> **Snapshot**
> 
> > And second, is it possible to get a snapshot of the dept of the orderbook?
> 
> Do you mean access to the history ?
> 
> As far as I know you can`t access to the orderbook history through the API.
> 
> But you can get the `dept` in real-time.

@Chavithra I'm surprised to read by accident in this issue report that the `fetch_data()` method can also deliver ask and bid **volume**. This is not part of the [documentation](https://github.com/Chavithra/degiro-connector#26-how-to-subscribe-to-a-data-stream-).
I tried to add `"AskVolume"` and `"BidVolume"` to the array with subscriptions, and they were returned. 👍
Can you please update the documentation, to show a complete overview of parameters to be requested?
Thanks for this awesome API.

**Comment by Chavithra** [comment]
@funnel20 : you are right about the doc.

PR are welcome if you want to help improving this library.

**Comment by funnel20** [comment]
I'm happy to contribute for the docu, but please understand that I don't have the knowledge about the details of DeGiro API.
So are there any other parameters than `'AskVolume'` and `'BidVolume'` for the `fetch_data()` method that you are aware of?

**Comment by 123m321** [comment]
> I'm happy to contribute for the docu, but please understand that I don't have the knowledge about the details of DeGiro API.
> So are there any other parameters than `'AskVolume'` and `'BidVolume'` for the `fetch_data()` method that you are aware of?

I wonder if the highest and lowest price of the day (this is available on the website) can be fetched?

**Comment by 123m321** [comment]
> > I'm happy to contribute for the docu, but please understand that I don't have the knowledge about the details of DeGiro API.
> > So are there any other parameters than `'AskVolume'` and `'BidVolume'` for the `fetch_data()` method that you are aware of?
> 
> I wonder if the highest and lowest price of the day (this is available on the website) can be fetched?

HighPrice and LowPrice work as well.

**Comment by Chavithra** [comment]
You can use something like this :
- A1Price
- B1Price
