### ISSUE TITLE
order entry fails in a product

### ISSUE THREAD

**Issue by 123m321** [Chavithra/degiro-connector#39]
I tried sending orders, and everything worked fine. Stocks, ETF's, buying and selling, great.

But there's one product which fails for me. The order isn't refused, it just gives no confirmation. It gives this debug text:

CRITICAL:degiro_connector.trading.actions.action_check_order:<Response [404]>
CRITICAL:degiro_connector.trading.actions.action_check_order:404 Client Error: Not Found for url: https://trader.degiro.nl/trading/secure/v5/checkOrder;jsessionid=51F9CB97CE11034CB87584687127AD90.prod_b_127_2?intAccount=[_hiddenintnr_]&sessionId=51F9CB97CE11034CB87584687127AD90.prod_b_127_2

order is:
price: 134.0
product_id: 600015811
size: 25.0
time_type: GOOD_TILL_CANCELED

I've tried with adjusting the price and the size, but nothing worked. 

This is the error message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/nx/0zjw32n90612p_zrm4ln3rxw0000gn/T/ipykernel_30912/3981454778.py in <module>
     52 print (checking_response)
     53 # EXTRACT CONFIRMATION_ID
---> 54 confirmation_id = checking_response.confirmation_id
     55 
     56 # EXTRACT OTHER DATA

AttributeError: 'NoneType' object has no attribute 'confirmation_id'

I tried to use a work around. I entered an order in this product manually in the app. That works as usual. Then I tried to change the order with the Order Update. But unfortunately, no luck. Received the same CRITICAL debug text.

**Comment by Chavithra** [comment]
Hello there,

was not able to find this product in Degiro`s website :
- `product_id` : `600015811`

Are you sure this product exists ?

**Comment by 123m321** [comment]
Absolutely, I just tried with the chart.py in Jupyter and received this:

It's a kind of bond - and maybe the currency thing is a problem? It's in euro but it's traded as percentage.

`{'requestid': '1',
 'start': '2021-12-01T00:00:00',
 'end': '2021-12-07T00:00:00',
 'resolution': 'P1D',
 'series': [{'expires': '2021-12-08T09:20:59.6754964+01:00',
   'data': {'issueId': 600015811,
    'companyId': 129333,
    'name': 'Rabobank Certificaat',
    'identifier': 'issueid:600015811',
    'isin': 'XS1002121454',
    'alfa': 'RABO',
    'market': 'XAMS',
    **'currency': None,**
    'type': 'OBL',
    'quality': 'REALTIME',
    'lastPrice': 139.29,
    'lastTime': '2021-12-08T09:05:38',
    'absDiff': -0.01,
    'relDiff': -7e-05,
    'highPrice': 139.29,
    'highTime': '2021-12-08T09:05:38',
    'lowPrice': 139.0,
    'lowTime': '2021-12-08T09:00:00',
    'openPrice': 139.0,
    'openTime': '2021-12-08T09:00:00',
    'closePrice': 139.0,
    'closeTime': '2021-12-08T09:00:00',
    'cumulativeVolume': 115100.0,
    'previousClosePrice': 139.3,
    'previousCloseTime': '2021-12-07T17:17:43',
    'tradingStartTime': '09:00:00',
    'tradingEndTime': '17:40:00',
    'tradingAddedTime': '00:25:00',
    'lowPriceP1Y': 126.61,
    'highPriceP1Y': 147.0,
    'windowStart': '2021-12-01T00:00:00',
    'windowEnd': '2021-12-07T00:00:00',
    'windowFirst': '2021-12-01T00:00:00',
    'windowLast': '2021-12-07T00:00:00',
    'windowHighTime': '2021-12-07T00:00:00',
    'windowHighPrice': 139.3,
    'windowLowTime': '2021-12-01T00:00:00',
    'windowLowPrice': 137.0,
    'windowOpenTime': '2021-12-01T00:00:00',
    'windowOpenPrice': 135.75,
    'windowPreviousCloseTime': '2021-11-30T00:00:00',
    'windowPreviousClosePrice': 136.0,
    'windowTrend': 0.02426470588235294},
   'id': 'issueid:600015811',
   'type': 'object'}]}`

**Comment by Chavithra** [comment]
Note that these two elements are different :
- issue id
- product id
