### ISSUE TITLE
What is the best way to determine whether an order is executed and against which price?

### ISSUE THREAD

**Issue by funnel20** [Chavithra/degiro-connector#41]
I'm able to create and confirm an order based on your [documentation](https://github.com/Chavithra/degiro-connector#41-how-to-create-an-order-).

When trading on the DeGiro website, once an order is executed, a popup is shown briefly.
Is there a way to subscribe to this event via the connector?

Or should we poll actively to see the changes.
For example to [retrieve pending orders](https://github.com/Chavithra/degiro-connector#51-how-to-retrieve-pending-orders-), and when the `id` is not in, assume it's executed.

Or via [OrdersHistory](https://github.com/Chavithra/degiro-connector#54-how-to-retrieve-the-ordershistory-) or [TransactionsHistory](https://github.com/Chavithra/degiro-connector#55-how-to-retrieve-the-transactionshistory-)?

**Comment by Chavithra** [comment]
I think you are referring at this feature from the website :
- after : creating an Order
- is display : a notification pop-in

Notification will let you now that an Order as been created.

As magic this notification looks like it seems to be done by :
- retrieving `pending Orders`
- every 2 seconds or so

**Comment by funnel20** [comment]
I was not referring to the confirmation popup that the order is created. 
I'm referring tot the 2nd popup, that informs that the order is executed against price X.

**Comment by Chavithra** [comment]
Do you have a capture of the location of this "2nd popup" ?

**Comment by funnel20** [comment]
Not for now, but the flow on the DeGiro website is quite self-explanatory:

1. When creating an order, it will be shown in the left table Outstanding, while the confirmation popup "new order created" is shown briefly:
<img width="652" alt="Screenshot 2021-12-08 at 10 31 13" src="https://user-images.githubusercontent.com/2139844/145184085-29036f2e-2682-401b-8d39-fb8e7633e7d8.png">

2. When the target price is met and the order is executed, a confirmation popup "order executed against pice X" is shown briefly, while the order is moved to the right column, where it shows the execution price (since that can be different than the target price in the original order)

**Comment by Chavithra** [comment]
Ok got it.

Oustanding : `orders`
Lastest Transactions : `transactions`

Just checked how the website is doing.

It still seems to use this endpoint : 
- `trading/secure/v5/update`

That you can consume with the method `update`.

**Comment by funnel20** [comment]
Awesome, I'll try this out.
Just for my understanding, is the `get_update()` used as a single call with a single answer, or is it more similar to `fetch_data()` as a a data stream, which will send updates once they occur?

**Comment by Chavithra** [comment]
Not exactly : fetch_data uses long polling.

Here this is just refreshing : the website seems to reload the data every 2 secondes.

**Comment by funnel20** [comment]
I have tried this, and I see the recent transactions.
What is the meaning of the  value for parameter `last_updated`? 
I.e. what if set to a value other dan `0`?

**Comment by Chavithra** [comment]
You need to send back send back the `last_updated` you received.

I think this is how this `endpoint` avoid sending you the same data twice.

**Comment by funnel20** [comment]
This is how we've implemented it after placing an order:

```
# IMPORTANT
# The response doesn't show any details whether an order was executed, only that the order is accepted.
# To check whether the order is executed and for what price, 2 events should be started:
#
# 1) Request pending orders via `get_update()` with a list that contains `Update.Option.ORDERS`
#       This returns an array with pending orders, including the order ID. Keep polling while the order ID is present in the ID.
#       Once the order is not present (this can already be at the first request when the order was executed immediately), 
#       any of these 2 events have occured:
#           a) The order has been deleted
#           b) The order has been executed
#       To determine whether it's deleted or executed, the Transaction history should be requested:
#
# 2) Request the Transaction History for today via `get_transactions_history()`
#       Unfortunately this array doesn't contain the order ID. 
#       So we need to filter on the ticker (`productId`), amount and action for transactions that were created after the confirmation date of the order (as returned by `confirm_order()`). 
```
We even take into account that the order might be executed by multiple transactions.

**Comment by Chavithra** [comment]
> This is how we've implemented it after placing an order:
> 
> ```
> # IMPORTANT
> # The response doesn't show any details whether an order was executed, only that the order is accepted.
> # To check whether the order is executed and for what price, 2 events should be started:
> #
> # 1) Request pending orders via `get_update()` with a list that contains `Update.Option.ORDERS`
> #       This returns an array with pending orders, including the order ID. Keep polling while the order ID is present in the ID.
> #       Once the order is not present (this can already be at the first request when the order was executed immediately), 
> #       any of these 2 events have occured:
> #           a) The order has been deleted
> #           b) The order has been executed
> #       To determine whether it's deleted or executed, the Transaction history should be requested:
> #
> # 2) Request the Transaction History for today via `get_transactions_history()`
> #       Unfortunately this array doesn't contain the order ID. 
> #       So we need to filter on the ticker (`productId`), amount and action for transactions that were created after the confirmation date of the order (as returned by `confirm_order()`). 
> ```
> 
> We even take into account that the order might be executed by multiple transactions.

Who is « we » ?

I think this can be more straightforward.

If I remember right « get_update » can let you know that the order was executed.

But you need to provide the « last_update ».

**Comment by funnel20** [comment]
@Chavithra Well, "we" is a group of friends who are using your awesome connector into a project. I recently helped you with PR https://github.com/Chavithra/degiro-connector/pull/42 .

There were some issues processing `trading_api.get_update()`, hence this is what we came up with.
It works for now, just wanted to inform other users about this, as it provides at least an answer to the issue (maybe not *the best*)

**Comment by Chavithra** [comment]
@funnel20 I think I know how to integrate this "order state detection feature".

But I don't have the time for this yet.

If you are up for the challenge we can brainstorm a specification for this together.

**Comment by funnel20** [comment]
@Chavithra I've finally found a way to link the order id and transaction id.
Once I've finished my prototype, I'll post my findings here.

**Comment by richardbeumer** [comment]
@funnel20 I'm very curious about the way you link order_id and transaction_id. Is there any followup?

**Comment by funnel20** [comment]
> @funnel20 I'm very curious about the way you link order_id and transaction_id. Is there any followup?

Unfortunately not, since we have put our project on halt.
