### ISSUE TITLE
Fetch the close price?

### ISSUE THREAD

**Issue by 123m321** [Chavithra/degiro-connector#45]
Within the portfolio I can retrieve the close price from stocks ('closePrice' in the portfolio df).

But from the quotecast part, I can't find the ClosePrice data. But I have the feeling it must be there, somehow? If I add ClosePrice to the quotecast, it gives no error. But also returns no data.

**Comment by Chavithra** [comment]
I think it's called : `PreviousClosePrice`

**Comment by 123m321** [comment]
Check, will add it to the readme
