### ISSUE TITLE
Info gui Degiro

### ISSUE THREAD

**Issue by segnalisys** [Chavithra/degiro-connector#47]
I was considering around for zero commissions and but the platform they have is too slow in placing orders. I came across this api but I'm not a programmer and I wanted to ask you but is it possible to create a GUI interface for order entry? in practice it consists of the book where the quantities and the price are entered and the window where the orders entered appear. The platform I use is written in java I attach a photo to make you understand what I mean. Thank you
![Degiroint](https://user-images.githubusercontent.com/34609559/146347252-9949394b-a438-4425-8da3-acfbbc9df0de.jpg)

**Comment by Chavithra** [comment]
Hello,

there is no `gui` with this library.


You can access some Degiro's features with this tool :
- https://github.com/GamestonkTerminal/GamestonkTerminal

It works on `command line`.

I am not certain to understand which features you are looking for.

Feel free to reach me on `Discord`.

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to open a new one if you have more questions.
