### ISSUE TITLE
Local variable referenced before assignment in action confirm order

### ISSUE THREAD

**Issue by Nearata** [Chavithra/degiro-connector#48]
package version: **2.0.11**

file: **action_confirm_order.py**
line: **148**

seems already fixed in main, but there's no update with the new changes on pypi

**Comment by Chavithra** [comment]
Hello there,

can you send an example of code which crashes with version `2.0.11` ?

Thanks

**Comment by Nearata** [comment]
Hello!

I can confirm that's fixed in `2.0.12`.

Thank you!
