### ISSUE TITLE
Don't send indexId on ProductSearch.RequestStocks if not provided

### ISSUE THREAD

**Issue by enekochan** [Chavithra/degiro-connector#5]
The `stocks` endpoint in `product_search` has an `indexId` parameter that is optional. If I call the `ProductSearch.RequestStocks` function without it:

``` python
request_stock = ProductSearch.RequestStocks(
    isInUSGreenList=False,
    stockCountryId=846,
    offset=0,
    limit=10,
    requireTotal=True,
    sortColumns='name',
    sortTypes='asc',
)
```

A default value of `0` is asigned to it in the request:

`/product_search/secure/v5/stocks?stockCountryId=846&limit=10&requireTotal=True&sortColumns=name&sortTypes=asc&isInUSGreenList=False&indexId=0&searchText=&offset=0&intAccount=xxx&sessionId=xxx`

And the API returns this error:

``` json
{"errors":[{"text":"No corresponding model found"}]}
```

I'm new to Python and never used Google Protocol Buffers (which is what it seems you are using) so may be I'm doing something wrong. I tried modifying the `trading/pb/trading_pb2.py` file `_PRODUCTSEARCH_REQUESTSTOCKS` descriptor to no avail.

I've also seen that the pb files are generated from a file called `trading/pb/trading.proto` that is not there. Should I need it if I wanted to change the descriptors?

**Comment by Chavithra** [comment]
Hello there,

thanks for reporting this bug.

I have updated the library.

Can you tell me if that works on your side too ?

**Comment by enekochan** [comment]
Yes, it works fine now :) Thanks!
