### ISSUE TITLE
KeyError: 'intAccount' for specific account

### ISSUE THREAD

**Issue by Abbetjen** [Chavithra/degiro-connector#53]
Hi! I'm an accountant building dashboards in Power BI and was able to use the connector to fetch data from DeGiro into Power BI. Great work (especially considering I don't know any Python) !

I'm using different DeGiro accounts to get data from, but somehow for one account I keep getting a'  KeyError: "intAccount" when trying the fetch the client_details table. When I use the same lines with different credentials it works just fine. Any idea what might cause this issue?

Some additional info: I use  the expample "client_details_table.py" to get the details. It runs fine for all accounts but one. When I only extract "Client_details_pretty" for the faulty account it works just fine.

**Comment by Chavithra** [comment]
Hello Abbetjen,

can you send the error you have ?

Thanks

**Comment by Chavithra** [comment]
Closing this issue.

It would be great to know more about your use case.

Feel free to open a new issue if you still can’t get what you want.
