### ISSUE TITLE
ActionConfirmOrder.confirm_order does not return interpretable error message

### ISSUE THREAD

**Issue by e9henrik** [Chavithra/degiro-connector#55]
When the order confirmation fails (can be due to eg. tick size being wrong, connection with exchange down, maintenance window etc) the order confirmation fails scilently and returns none.

Changing the code below in action_confirm_order.py will instead return the error message in a dictionary (making it possible for example to get the correct tick size, if that's the cause of the error)

``` python
<original>
        try:
            response_raw = session.send(prepped, verify=False)
            response_raw.raise_for_status()
            response_dict = response_raw.json()
        except Exception as e:
            logger.fatal(response_raw)
            logger.fatal(e)
            return None
</original>
```
``` python
<modified>
        try:
            response_raw = session.send(prepped, verify=False)
            response_dict = response_raw.json()
            response_raw.raise_for_status()
        except Exception as e:
            logger.fatal(response_raw)
            logger.fatal(e)
            return response_dict
</modified>
```

**Comment by Chavithra** [comment]
Hello there,

looks like you are not having the latest code.

Which version are you using ?

**Comment by e9henrik** [comment]
Thanks for pointing that out, I was using 2.0.9.

**Comment by e9henrik** [comment]
Hi again, I now checked 2.0.13, and this is indeed fixed for confirm_order(). Super!

check_order needs a similar fix, as degiro handles some errors already at checking (such as order size multiple).

``` diff
*** /.venv/Lib/site-packages/degiro_connector/trading/actions/action_check_order_orig.py	Wed Jan  5 23:57:47 2022
--- /.venv/Lib/site-packages/degiro_connector/trading/actions/action_check_order.py	Thu Jan  6 00:15:12 2022
***************
*** 139,145 ****
              text = getattr(response_raw, "text", "No text found.")
              logger.fatal(status_code)
              logger.fatal(text)
!             return None
          except Exception as e:
              logger.fatal(e)
              return None
--- 139,150 ----
              text = getattr(response_raw, "text", "No text found.")
              logger.fatal(status_code)
              logger.fatal(text)
!             if raw is True:
!                 response_dict = response_raw.json()
!                 logger.fatal(response_dict)
!                 return response_dict
!             else:
!                 return None
          except Exception as e:
              logger.fatal(e)
              return None
```

Thanks alot for creating this great package!

**Comment by Chavithra** [comment]
Hi, contributions are welcome.

You can make a PR with your code update.

Otherwise will see that later this month.

**Comment by funnel20** [comment]
Please note that this is related to https://github.com/Chavithra/degiro-connector/issues/54 to improve fault handling consistently. Also for default `raw` = `False`.

**Comment by Chavithra** [comment]
Closing this issue since it is discussed in #54.
