### ISSUE TITLE
Querying "News" section request

### ISSUE THREAD

**Issue by iv-vz** [Chavithra/degiro-connector#6]
Hi guys, beautiful work!! thank you very much for making it open.

Would it be actually possible to access the news api? or is there any limitation? 

Best regards,
Ivan

**Comment by Chavithra** [comment]
Hi,

I have an answer and a question for you.

**ANSWER**
I have planned to add news endpoints.

But for the following reason it is not yet available :
- I don't need this feature for myself currently.
- I didn't know that someone was interested in it.

**QUESTION**
These are all the news related endpoints that I have found last time that I have checked :
- latest-news : latest news about all the companies.
- news-by-company : news related to a specific company.
- top-news-preview : some news preview about all the companies.

Can you tell me which ones you are interested in ?

Thanks

**Comment by Chavithra** [comment]
Closed this issue feel free to open a new one if needed.
