### ISSUE TITLE
Can't run the connection.py example on Google Colab

### ISSUE THREAD

**Issue by realmistic** [Chavithra/degiro-connector#61]
Hi!

I've tried to run your basic connection example ( https://github.com/Chavithra/degiro-connector/blob/main/examples/trading/connection.py) and received the following error:

**ImportError: cannot import name 'final' from 'typing' (/usr/lib/python3.7/typing.py)**
  on the line ("from typing import Dict, final")

Here is my Colab notebook (it can be copied easily and tested) : https://colab.research.google.com/drive/1f3yIlVOzFn8PIP9K0wKIlXvNCskrJs4e#scrollTo=oeFMK2Tx8NHF

I suspect this is because Google Colab uses Python 3.7.12, while your code needs 3.8? or 3.10?

I couldn't find any easy method how to update Python in Google Colab without breaking it.

Any ideas how to solve this?

Thanks,
Ivan

**Comment by Chavithra** [comment]
Hello didn’t know `final` decorator was so recent.

It’s seems to be available starting from python 3.8.

Will consider removing this decorator since it’s just `typing`.

**Comment by realmistic** [comment]
Thanks, Chavithra!
I'll wait that to happen

**Comment by Chavithra** [comment]
Hi, I just removed the usage of `final` decorator.

Let know if you still have issues with Colab.

Thanks

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to open another one if there still issue with `Google Colab`.

**Comment by realmistic** [comment]
Thanks! It is working on my side now in Colab
