### ISSUE TITLE
Integrate algo modules(BackTrader, TensorTrade, FreqTrade) in this api

### ISSUE THREAD

**Issue by Deliki** [Chavithra/degiro-connector#63]
How can we integrate the feed of data from this API in several common used Algo modules e.g. 
- Backtrader (https://github.com/backtrader/backtrader), 
- FreqTrade for Telegram interactivity ( https://github.com/freqtrade/freqtrade )
- TensorTrade (https://github.com/tensortrade-org/tensortrade). 
Maybe even add YFinance (Yahoo) as additional datafeed to support more flexibility in US fundamental data?

There are certain buy and sell functions that should be aligned and plotted in backtrader. 
Any ideas in an approach of this logic and what could be a first step, how would this example look like?

**Comment by Chavithra** [comment]
Hello @Deliki,

this will vary depending the library you are trying to integrate the data with.

I guess you can use the DataFrame version of the data and consume it with these libraries.

This goes a deeper than this library scope.

Closing this issue for now.

Feel free to open a new issue if you have other questions or need a precision on this one.

Thanks
