### ISSUE TITLE
OHLC chart data values are not matching with the API pulled values

### ISSUE THREAD

**Issue by hamoudeh90** [Chavithra/degiro-connector#66]
Hi first of all thank you very much for your work!
I have tried to experiment a little with the library but I cannot seem to have the same values that are shown by Degiro's website on the charts. i have tried it on several stocks but can't seem to get the same values.
Here is the code I used to get the OHLC data for AAPL:

```quotecast_api = QuotecastAPI(user_token=user_token)

request = Chart.Request()
request.culture = "fr-FR"
request.period = Chart.Interval.P1D
request.requestid = "1"
request.resolution = Chart.Interval.PT1H
request.series.append("ohlc:vwdkey:AAPL.BATS,E")
request.tz = "EST"
request.override["resolution"] = "P1D"
request.override["period"] = "P1W"

chart = quotecast_api.get_chart(
    request=request,
    raw=False)

ChartHelper.format_chart(chart=chart, copy=False)
chart_df = ChartHelper.serie_to_df(serie=chart.series[0])
chart_df["timestamp"] = pd.to_datetime(chart_df["timestamp"]+3600, unit="s")
```

Here are the results from the API and a screenshot of the data on the website:

   timestamp        open        high         low       close
0 2022-02-01  173.891456  174.370854  172.103703  173.142397
1 2022-02-02  174.570603  175.329649  173.122423  174.810301
2 2022-02-03  174.285960  176.008795  173.641770  175.050000
3 2022-02-04  171.690000  172.900000  170.690000  172.520000

![Screenshot](https://user-images.githubusercontent.com/99208701/152847802-51600e59-906d-4e06-be69-6f9890e68820.jpg)

I would really appreciate it if anyone knows the reason for this discrepency.

Thank you very much!

**Comment by Chavithra** [comment]
Hello @hamoudeh90,

I don't know why but this seems to be not the case when you are using `issueid`.

```python
request.series.append("ohlc:issueid:350015372")
```

For some reason when the `vwdkey` is used it doesn't display the same result than the website.

Hope that helps

**Comment by Chavithra** [comment]
Closing this issue.

Feel free to open a new one if you have other questions.
