### ISSUE TITLE
Updating an existing stop loss order

### ISSUE THREAD

**Issue by coveritytest** [Chavithra/degiro-connector#70]
Can I update an existing stop loss order via:

```
order = Order(
    id=order_id,
    action=Order.Action.SELL,
    order_type=Order.OrderType.STOP_LOSS,
    price=stop_loss_price,
    product_id=int(product_id),
    size=size,
    time_type=Order.TimeType.GOOD_TILL_DAY,
)

trading_api.update_order(order=order)
```

or do I have to delete the existing stop loss order via:

`trading_api.delete_order(order_id=order_id)`

and set a new stop loss order?

**Comment by Chavithra** [comment]
Hello there,

**PRICE UPDATE**
you can update the price with `update_order`.

If you want to do more, like the `order_type` then you probably need to create another `Order`.

**STOP_PRICE**
As explained in the documentation when you use `STOP_LOSS` you need to use the `stop_price` field.

Hope that helps

**Comment by coveritytest** [comment]
Works like a charm, thanks. Didn't look thoroughly enough for the details.
