### ISSUE TITLE
Missing "estimates summaries"

### ISSUE THREAD

**Issue by facoptere** [Chavithra/degiro-connector#71]
Hi,
with this API, I can get the financial statement and ratios of a stock, but I can't find the "estimates summaries".
It is the second half of the tab "Analyst Views', the top half being handled properly  by get_company_ratios()

Example:
https://trader.degiro.nl/dgtbxdsservice/estimates-summaries/US61174X1090

It is possible to make it available?
Thanks

**Comment by Chavithra** [comment]
Hello @facoptere,

good idea.

Just release a new version with this feature.

Let me know if that works on your side.

Thanks

**Comment by facoptere** [comment]
It works.
Many thanks.
