### ISSUE TITLE
Cannot create a sell order. Error "{"errors":[{"text":"Method not allowed"}]}"

### ISSUE THREAD

**Issue by TommasoBendinelli** [Chavithra/degiro-connector#73]
Hello,

I am trying to create the following sell order:
```
order = Order(
        action=1,
        order_type=0,
        price=54.1,
        product_id=18364386,
        size=2,
        time_type=3,
    )

```
When trying to validate the order with
` 
checking_response = trading_api.check_order(order=order,raw=True)["data"]
`
I get a "None" response. If I click in the url popping up in the console, I get the following error:
{"errors":[{"text":"Method not allowed"}]}

**Comment by Chavithra** [comment]
Hello @TommasoBendinelli,

isn’t there a missing comma in the example ?

**Comment by TommasoBendinelli** [comment]
Thanks for pointing it out. I made a typo during edititing.

**Comment by Chavithra** [comment]
Got it, closing the issue.

If that happens again, having the debug log would be nice.

**Comment by TommasoBendinelli** [comment]
Hi, It happened again yesterday. How can I create the debug log?

**Comment by Chavithra** [comment]
Hi, you can  add this line at the beginning of your code :

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by TommasoBendinelli** [comment]
Great thanks, I will post the output when it happens again.

**Comment by coveritytest** [comment]
I do have these problems, too. Maybe it's related:

`2022-03-09 18:37:57,586 CRITICAL MainThread      400
2022-03-09 18:37:57,586 CRITICAL MainThread      {"errors":[{"text":"order.error.128"}]}

2022-03-14 11:42:02,077 CRITICAL MainThread      500
2022-03-14 11:42:02,077 CRITICAL MainThread      {"errors":[{"text":"Internal server error"}]}`

**Comment by TommasoBendinelli** [comment]
I also don't have more debug outputs. Apparently, it seems to happen when I am trying to sell something bought on the same day.

**Comment by coveritytest** [comment]
I just found out that at least the

` {"errors":[{"text":"Internal server error"}]}`

error is gone, when I login to degiro once via browser. Should not be the case though I guess.

**Comment by Chavithra** [comment]
Closing this issue for now.

Feel free to open a new one if you can reproduce it in the future.

Thanks
