### ISSUE TITLE
[SECURITY] Enable TLS certificate validation

### ISSUE THREAD

**Issue by fl42** [Chavithra/degiro-connector#74]
Hello,

I don't understand the reasoning behind [disabling](https://github.com/Chavithra/degiro-connector/blob/main/degiro_connector/core/models/model_session.py#L27) TLS certification validation.
This allows MITM attacks.

Requests module can connect to Degiro's servers with default settings:
```py
import requests
req = requests.get("https://trader.degiro.nl")
print(req)
```

Furthermore, Degiro follows TLS best practices as it is [A+ rated](https://www.ssllabs.com/ssltest/analyze.html?d=trader.degiro.nl).

Could you please enable TLS certificate validation to prevent MITM attacks?

Thanks

**Comment by nine1zero** [comment]
that would be great !! many thanks

**Comment by Chavithra** [comment]
Hello there,

that will take some time : because of the tests required.

If someone wants to help on this : feel free to join me on Discord or to open a PR.

Thanks

**Comment by facoptere** [comment]
This issue is being handled by someone? If not I can take this ticket (at least I can  try...).

**Comment by nine1zero** [comment]
I dont think so, try reach out Chavithra. I would help but my coding skills are not enough :(

**Comment by Chavithra** [comment]
Yes !

**Comment by Chavithra** [comment]
@facoptere Thanks again for this PR

I think this issue is solved now.

@facoptere Is there a way we can get in touch ? discord or something

**Comment by facoptere** [comment]
Hi @Chavithra. I just sent you a message on discord.
