### ISSUE TITLE
Retrieve Portfolio content from the past

### ISSUE THREAD

**Issue by zerola** [Chavithra/degiro-connector#75]
Hi, maybe I am missing it but I can't find a way how to retrieve a Portfolio content from some day in the past. In DEGIRO website it is possible to export a portfolio how it looked at a specific day in the history.

In the examples, I see only:
`request_list.values.extend(
            [
                Update.Request(option = Update.Option.PORTFOLIO, last_updated = 0)
            ]
        )`

Is there a way how to pass a date to the API call? Thank you.

**Comment by Chavithra** [comment]
Hello @zerola,

that is not a feature that I am aware of : either from the API or from the website.

A solution that might work : 
- Store Portfolio at some point of time
- Use TransactionsHistory or OrdersHistory to calculate the Portfolio state at any given time

Hope that answer your question.

**Comment by zerola** [comment]
Hi @Chavithra,

in my (czech version) of DEGIRO, under the Portfolio section I have an Export button:

![Screenshot from 2022-03-08 15-14-18](https://user-images.githubusercontent.com/5671078/157255591-91399352-1f46-4b62-9b42-63bb4c791703.png)

When clicked, I can select a date and output format and it exports my portfolio state from that date in the history.
![Screenshot from 2022-03-08 15-15-49](https://user-images.githubusercontent.com/5671078/157255726-83413ebf-0f9b-4995-8203-3d6b88856c0f.png)

Perhaps it helps ... Or is DEGIRO calculating it on the fly using the transaction history?
Thank you.

**Comment by Chavithra** [comment]
Nice, will take a look !

**Comment by Chavithra** [comment]
Hi I have added this to the version `2.0.18`.

The documentation was also updated : take a look at `PositionReport` feature.

**Comment by zerola** [comment]
Excellent, looks like exactly what I needed. I will test it soon. For now, I will close the issue. Thanks for a quick implementation.
