### ISSUE TITLE
EstimatesSummaries  error

### ISSUE THREAD

**Issue by Rubengarber** [Chavithra/degiro-connector#76]
A fantastic job. 
I'm passing all the features to Jupiter Notebook to see the result and it failed me:

# FETCH DATA
product_isin = "FR0000131906"
estimates_summaries = trading_api.get_estimates_summaries(
    product_isin=product_isin,
    raw=False,
)

>>>
DEBUG:degiro_connector.trading.api:CALLING __GETATTR__, on item : get_estimates_summaries

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-afca8f2bc7e2> in <module>
      3 estimates_summaries = trading_api.get_estimates_summaries(
      4     product_isin=product_isin,
----> 5     raw=False,
      6 )

TypeError: 'NoneType' object is not callable
----------------------------------------------------------------------------1

And reviewing the documentation I have found that

8.7. How to get : Agenda ?     and     8.8. How to get : EstimatesSummaries ?

have the same sample code

**Comment by Chavithra** [comment]
Hello there,

**Documentation**
Nice catch on the documentation : fixed it.

**Example file**
The example file I have put there is working on my side :
- examples\trading\estimates_summaries.py

So either :
- the code you tried on your Jupiter Notebook as differences with this example file
- either some

**Your full code**
Can you show the full code you are trying to run ?

**Comment by Rubengarber** [comment]
Thank you for your immediate response. 
You are right, I have tested the code of "estimates_summaries.py" in Spyder and in Jupyter.
In Spyder it works correctly and in Jupyter it gives error, running under the same kernel. 

CODE
product_isin = 'FR0000131906'
estimates_summaries = trading_api.get_estimates_summaries(
                                                            product_isin=product_isin, 
                                                            raw=False)


ERROR IN JUPYTER:
DEBUG:degiro_connector.trading.api:CALLING __GETATTR__, on item : get_estimates_summaries

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-511f2a42c9ee> in <module>
      1 estimates_summaries = trading_api.get_estimates_summaries(
      2                                                             product_isin=product_isin,
----> 3                                                             raw=False)

TypeError: 'NoneType' object is not callable
_________________________________________________________________________________

**Comment by Chavithra** [comment]
This example also works in my `Jupyter Notebook`.

So this is possibly just local settings related.

Closing this issue for now.

Feel free to open a new one if you find more about this.
