### ISSUE TITLE
Favourite list management

### ISSUE THREAD

**Issue by facoptere** [Chavithra/degiro-connector#79]
Hi @Chavithra ,

Could you add some features to edit favourite lists?

- **Create a new favourite list:**

> `POST https://trader.degiro.nl/pa/secure/favourites/lists?intAccount=xxxxx&sessionId=yyyyy`
> json payload:` {name:"<LIST NAME>"}`
> json return: ` {data:<LIST ID>}`

- **Discard an existing favourite list:**

> `DELETE https://trader.degiro.nl/pa/secure/favourites/lists/<LIST ID>?intAccount=xxxxx&sessionId=yyyyy`

- **Add / Remove a product to an existing favourite list:**

> `PUT / DELETE https://trader.degiro.nl/pa/secure/favourites/lists/<LIST ID>/products/<PRODUCT ID>?intAccount=xxxxx&sessionId=yyyyy`
	

Many thanks for your great work!

**Comment by Chavithra** [comment]
Hey @facoptere, good idea.

Will check that when I will have some time during the month.

**Comment by Chavithra** [comment]
Done.

**Comment by facoptere** [comment]
Thanks. It works. Please note that intAccount is mandatory for all these.
