### ISSUE TITLE
Error on quotecast_api.logout()

### ISSUE THREAD

**Issue by nine1zero** [Chavithra/degiro-connector#80]
First of all, maaaany thanks for your work!!  :)
It works likle a charm, i have just few small problems

I wrote a script for monthly buying with dollar-cost avg a global etf, with these workflow:

- **trading_api.connect()**
- trading_api.get_products_info _(to get the vwdId anche check product)_
- trading_api.get_update _(to get the portofolio and available cash)_
- trading_api.get_transactions_history _(to check if already done a transaction in the months)_
- **quotecast_api.connect()** 
- quotecast_api.fetch_metrics _(to get real time price for the vwdId to buy)_
- **quotecast_api.logout()**
- trading_api.confirm_order _(to buy based on current price/cash/breakeven)_
- **trading_api.logout()**

everything seems working fine, but if I add the quotecast_api.logout() I am getting this error...I am doing something wrong?
In general the workflow is correct?

Many thanks
```
DEBUG:urllib3.connectionpool:https://degiro.quotecast.vwdservices.com:443 "POST /CORS/90c918c6-9ec9-4785-ade8-eefb5511a819 HTTP/1.1" 200 0
DEBUG:degiro_connector.core.models.model_session:session:getter: MainThread
DEBUG:urllib3.connectionpool:https://degiro.quotecast.vwdservices.com:443 "GET /CORS/90c918c6-9ec9-4785-ade8-eefb5511a819 HTTP/1.1" 200 184
DEBUG:degiro_connector.quotecast.api:CALLING __GETATTR__, on item : logout
Traceback (most recent call last):
  File "..Test.py", line 177, in <module>
    quotecast_api.logout()
TypeError: 'NoneType' object is not callable
```

**Comment by Chavithra** [comment]
Hello @nine1zero,

the `Action` called `logout` is not implemented inside the following module :
- `degiro_connector.quotecast.api`

I am not even sure that the endpoint to that exists.

Quotecast endpoint has a really short timeout : after a dozen of seconds or so you will be disconnected automatically.

**Comment by nine1zero** [comment]
ok thank you! just proposed the update of the docs, where was mentioned the "quotecast_api.logout()"
