### ISSUE TITLE
Historical intraday data

### ISSUE THREAD

**Issue by kantundpeterpan** [Chavithra/degiro-connector#86]
Hello,

I am trying to get historical intraday OHLC data via the degiro API (1 minute or 5 minute level).
This works fine for the 1W period but I keep getting strange results (I suppose intended by degiro) for anything longer than 1 month.
Upon on increasing the period I get intraday data for first couple of days and only EOD data for the rest (see the chart below which gives the number of datapoints per day). Is there any hack around this?

![](https://user-images.githubusercontent.com/49794000/174446596-e4da0dad-c280-4d6c-8551-7ceb295624fd.png)

**Comment by Chavithra** [comment]
Hello @kantundpeterpan,

thank you for your interest in this library.

> This works fine for the 1W period but I keep getting strange results (I suppose intended by degiro) for anything longer than 1 month.

I think this is the intended behaviour of Degiro's API:
- They might not have this data available.
- They might not want to share it.

Let me know if you find a solution for that.

Thanks
