### ISSUE TITLE
Running into issue with totp_secret_key

### ISSUE THREAD

**Issue by johan-beemsterboer** [Chavithra/degiro-connector#87]
Hi,

I'm struggling to get my user_token. I have inserted my user_name and password, but I get a concatenation error:

Here's the errors:
` File "D:\degiro-connector-main\examples\trading\client_details_table.py", line 34, in <module>
    trading_api.connect()
  File "C:\Python\Python310\site-packages\degiro_connector\core\abstracts\abstract_action.py", line 73, in __call__
    return self.call(*args, **kwargs)
  File "C:\Python\Python310\site-packages\degiro_connector\trading\actions\action_connect.py", line 121, in call
    connection_storage.session_id = self.get_session_id(
  File "C:\Python\Python310\site-packages\degiro_connector\trading\actions\action_connect.py", line 63, in get_session_id
    one_time_password = str(otp.get_totp(totp_secret_key))
  File "C:\Python\Python310\site-packages\onetimepass\__init__.py", line 167, in get_totp
    return get_hotp(
  File "C:\Python\Python310\site-packages\onetimepass\__init__.py", line 114, in get_hotp
    print ("secret 2 = " + secret)
TypeError: can only concatenate str (not "bytes") to str`

What am I doing wrong?

**Comment by Chavithra** [comment]
Hello there,

is it possible to share the code you are running?

Hidding the credentials of course.

Thanks

**Comment by johan-beemsterboer** [comment]
Hi, I'm running examples\trading\client_details_table.py, using this config file:


```
{
    "user_token":123,
    "int_account":1425857,
    "username":"USERNAME",
    "password":"PASSWORD",
    "totp_secret_key": "otpauth://totp/DEGIRO:jjbeemsterboer?algorithm=SHA1&issuer=DEGIRO&secret=SECRET&digits=6&period=30"

}
```

When I deactivate 2FA it does work. I tried running it as follows as well:


```
{
    "user_token":123,
    "int_account":1425857,
    "username":"USERNAME",
    "password":"PASSWORD",
    "totp_secret_key": "SECRET"

}
```

**Comment by Chavithra** [comment]
Hi @johan-beemsterboer.

normally your second try should have worked.

This one:
```json
{
    "user_token":123,
    "int_account":123,
    "username":"USERNAME",
    "password":"PASSWORD",
    "totp_secret_key": "SECRET"

}
```

Closing this GitHub Issue.

Feel free to open a new one if you still have 2FA issues.

Thanks
