### ISSUE TITLE
Chart data API is a bit cryptic on how it works.

### ISSUE THREAD

**Issue by codecnotsupported** [Chavithra/degiro-connector#9]
The README does contain a example how to get chart data.
But doesn't mention what types of series data there are. 
Or for that matter what the number `360148977` means. ( Probably the product ID )
Or how to decode the integer timestamps. (
I took a guess how it works. Take the 'times' timestamp convert it to a integer and use it as a offset.
```
from datetime import datetime
date = chart['series'][1]['times'][:-5]  # contains '2020-03-13T00:00:00/PT1S'
offset = datetime.strptime(date, "%Y-%m-%dT%H:%M:%S")
data_point = chart['series'][1]['data'] # contains: [32400, 6.9] 1st is the timestamp, 2nd the data, which is the price in this case.
timestamp = data_point[0]
corrected_timestamp = offset.timestamp() + timestamp * 1 # you multiply the timestamp with the resolution converted to seconds.
# In case you used PT15S multiply by 15, PT5M is 5 min converted to seconds is 300, so multiply the timestamp by 300 .
datetime.fromtimestamp(corrected_timestamp)
```

**Comment by Chavithra** [comment]
Hello there,

I have split my answer in three parts : 
1. Type of series
2. Issue id
3. How to get data points timestamp ?

**1. Type of series**
> @codecnotsupported
> The README does contain a example how to get chart data.
> But doesn't mention what types of series data there are.

Are you talking about the request to the API or the result ?

If you were talking about the request, you can find those in the examples : 
- issueid
- price
- ohlc
- volume

These are all the series types that I have found.

If you find more let me know.

**2. Issue id**
> @codecnotsupported
> Or for that matter what the number 360148977 means. ( Probably the product ID )

This number is not the product id : `360148977`.

The number `360148977` is the id of the stock : 
- name : `AIRBUS`
- product id : `96008`
- vwd_id / issueid : `360148977`

**3. How to get data points timestamp ?**
> @codecnotsupported
> I took a guess how it works. Take the 'times' timestamp convert it to a integer and use it as a offset.

I think you are right on how to calculate the timestamp for each data point.

Here is some code that I have made to check if that works :

```python
from datetime import datetime
from typing import List

def extract_times(serie: dict) -> str:
    times = serie['times']
    times = times.rsplit(sep='/', maxsplit=1)
    times = times[0]

    return times

def extract_resolution(serie: dict) -> str:
    times = serie['times']
    times = times.rsplit(sep='/', maxsplit=1)
    resolution = times[-1]

    return resolution

def resolution_in_seconds(resolution: str):
    unit = resolution[-1]
    units = int(resolution[2:-1])

    if unit == 'S':
        seconds_per_unit = 1
    elif unit == 'M':
        seconds_per_unit = 60
    elif unit == 'H':
        seconds_per_unit = 3600
    else:
        raise AttributeError('Unknown resolution')

    seconds = seconds_per_unit * units
    
    return seconds

def positions_to_timestamp(serie: str) -> List[List]:
    points = serie['data']
    points_timestamp = list()

    resolution = extract_resolution(serie=serie)
    resolution_s = resolution_in_seconds(resolution=resolution)

    times = extract_times(serie=serie)
    times_datetime = datetime.strptime(times, '%Y-%m-%dT%H:%M:%S')
    times_timestamp = times_datetime.timestamp()

    for (position, value) in points:
        time = position * resolution_s + times_timestamp
        points_timestamp.append([time, value])
    
    return points_timestamp

def positions_to_datetime(serie: str) -> List[List]:
    points_timestamp = positions_to_timestamp(serie=serie)
    points_datetime = list()

    for (timestamp, value) in points_timestamp:
        dt = datetime.fromtimestamp(timestamp)
        points_datetime.append([dt, value])
    
    return points_datetime

# SELECT THE RIGHT SERIE HERE
serie = chart['series'][1] 

points_timestamp = positions_to_timestamp(serie=serie)
points_datetime = positions_to_datetime(serie=serie)

for (time, value) in points_datetime:
    print(time, value)
```

Here is what this code display for  :

```
2021-03-12 09:00:00 12.24
2021-03-12 09:16:01.200000 12.22
2021-03-12 10:58:58.800000 12.31
2021-03-12 11:58:58.800000 12.35
2021-03-12 12:01:58.800000 12.375
2021-03-12 12:58:58.800000 12.365
2021-03-12 13:58:58.800000 12.335
2021-03-12 14:58:58.800000 12.315
2021-03-12 15:58:58.800000 12.355
2021-03-12 16:58:58.800000 12.335
2021-03-12 17:37:58.800000 12.32
```

I have used this parameters : 
- issueid = 360148977
- resolution = PT1H (one hour)
- period = P1D (one day)

**Comment by codecnotsupported** [comment]
1. Okay, I misunderstood and thought there were more series types.
2. Yes, I found out not too long ago before I saw your answer, little note for anyone else reading: vwd_id is named 'vwdIdSecondary' in favorites (`trading_api.get_favourites_list()`). 
3. Seems to work OK.

Closing the issue, you might want to add the functionality to convert from integer timestamp to datetime object.
