### ISSUE TITLE
Access to Order Book

### ISSUE THREAD

**Issue by crigault** [Chavithra/degiro-connector#93]
Hello Sir,

Thank you for your excellent work on your degiro-connector API. 
I would like to get the order book (ie depth of market) information that lists the first 10 ask and bid volumes and prices real time.
Is it currently possible with your API, like by using the data-stream, and how to do that exactly ?
If it's not currently possible, do you intend to implement it ?

Thanks for your answers
Sincerely
Cyrille

**Comment by traveler0027** [comment]
@crigault did you manage to get some info on this one?

**Comment by Chavithra** [comment]
Hi @crigault,

thank you for your interest in this library.

For the realtime access feature description, I encourage you to take a look at the following section of the current documentation:
- `2. Real-time data`

For the parameters available for the order-book bids/asks, they are listed here:
- https://github.com/Chavithra/degiro-connector/issues/37#issuecomment-1000540148
